### PR TITLE
Vb/newsletter embed autofill email

### PR DESCRIPTION
**Pull request by lindseydew**
## What does this change?

This implements the logic for auto-populating the newsletters sign-up form with a users email address if we already have that information into the newly refactored component. 

## Why?

There was work being done to refactor using an iframe for the sign up component https://github.com/guardian/dotcom-rendering/pull/10034 whilst this feature was being worked on. This adds the new functionality to the refactored branch. 

## Screenshots
daily

| Before      | After      |
| ----------- | ---------- |
| ![before][] | ![after][] |

[before]: https://example.com/before.png
[after]: https://example.com/after.png

### CODE REVIEW

**Review by abeddow91 — APPROVED** [review]
Looks great, thanks for refactoring this feature!! 🚀

**Comment by mxdvl** [comment]
The padding to the left of the **Sign Up** button seems unnecessary

**Comment by lindseydew** [comment]
Yeah @vlbee and I debated this. 

Could make the margin 0 in this case. Happy to raise a PR to do so?

**Comment by paperboyo** [comment]
Aloha! No idea if this PR caused it, but timing seems right. This is how it looks for me now when signed in:

image

And here Incognito:

image

(multiple browsers, OSes)

**Comment by lindseydew** [comment]
> Aloha! No idea if this PR caused it, but timing seems right. This is how it looks for me now when signed in:
> 
> image
> 
> And here Incognito:
> 
> image
> 
> (multiple browsers, OSes)

Hey, thanks for raising. This PR has only been merged into a feature branch, so it hasn't gone out live. 

It was introduced by this PR that was released yesterday: https://github.com/guardian/dotcom-rendering/pull/9990 
It is a known bug that is referenced here: https://github.com/guardian/dotcom-rendering/issues/10132 
This should be fixed by this refactor branch.

**Pull request merged**
