### PR TITLE
Add margin-bottom to merch-high and merch in Fronts and Articles

### PR DESCRIPTION
**Pull request by deedeeh**
## What does this change?

This PR adds more space to the bottom of the merch-high and merch containers.  

1. Added `12px` margin top and bottom to merch-high and merch in Fronts and Articles on mobile.
2. Added `0` margin and `20px` padding bottom to merch and merch-high in Articles and merch in Fronts on desktop.  

## Why?

Better UI before Black Friday!

## Screenshots

| Before      | After      |
| ----------- | ---------- |
| image | image |
| image | image |

[before]: https://example.com/before.png
[after]: https://example.com/after.png

### CODE REVIEW

**Comment by SiAdcock** [comment]
> I think the margin should be on the slot to be consistent with fronts-banners? And only when a non-merch ad is present aka doesn't have the class `.ad-slot--fluid` 

Agreed, you can probably update the [`merchandisingAdStyles`](https://github.com/guardian/dotcom-rendering/blob/c4c6b382b145aaf8a03f90ee4d784d2ee4f5c825/dotcom-rendering/src/components/AdSlot.web.tsx#L204-L207) class to achieve this

```
const merchandisingAdStyles = css`
	position: relative;
	min-height: ${adSizes.billboard.height}px;
	margin: 12px auto;

	${from.desktop} {
		margin: 0;
		padding-bottom: 20px;
	}
`;
```

I think the margin and padding [will be overridden](https://github.com/guardian/dotcom-rendering/blob/c4c6b382b145aaf8a03f90ee4d784d2ee4f5c825/dotcom-rendering/src/components/AdSlot.web.tsx#L154-L162) if the `.ad-slot--fluid` class is present.

**Comment by deedeeh** [comment]
> I think the margin should be on the slot to be consistent with fronts-banners? And only when a non-merch ad is present aka doesn't have the class `.ad-slot--fluid` Screenshot 2023-11-17 at 12 26 07

That is what I tried at the beginning but then I wasn't sure if we considered in-house ads in merch-high and merch slots because it looks very odd to have margin bottom in the grey container and not margin top. I also didn't know that `.ad-slot--fluid` should override the merchandising styling if it is present. 

I will try @SiAdcock suggestion.

**Comment by deedeeh** [comment]
> > I think the margin should be on the slot to be consistent with fronts-banners? And only when a non-merch ad is present aka doesn't have the class `.ad-slot--fluid`
> 
> Agreed, you can probably update the [`merchandisingAdStyles`](https://github.com/guardian/dotcom-rendering/blob/c4c6b382b145aaf8a03f90ee4d784d2ee4f5c825/dotcom-rendering/src/components/AdSlot.web.tsx#L204-L207) class to achieve this
> 
> ```js
> const merchandisingAdStyles = css`
> 	position: relative;
> 	min-height: ${adSizes.billboard.height}px;
> 	margin: 12px auto;
> 
> 	${from.desktop} {
> 		margin: 0;
> 		padding-bottom: 20px;
> 	}
> `;
> ```
> 
> I think the margin and padding [will be overridden](https://github.com/guardian/dotcom-rendering/blob/c4c6b382b145aaf8a03f90ee4d784d2ee4f5c825/dotcom-rendering/src/components/AdSlot.web.tsx#L154-L162) if the `.ad-slot--fluid` class is present.

I added your suggested change and I can always see in merch or merch-high this `.ad-slot--fluid` which like you said overrides the styling from `merchandisingAdStyles` because of the order of the css values. My question is how can we test that? I mean in which cases this change will be actually applied?

**Comment by Jakeii** [comment]
> > > I think the margin should be on the slot to be consistent with fronts-banners? And only when a non-merch ad is present aka doesn't have the class `.ad-slot--fluid`
> > 
> > 
> > Agreed, you can probably update the [`merchandisingAdStyles`](https://github.com/guardian/dotcom-rendering/blob/c4c6b382b145aaf8a03f90ee4d784d2ee4f5c825/dotcom-rendering/src/components/AdSlot.web.tsx#L204-L207) class to achieve this
> > ```js
> > const merchandisingAdStyles = css`
> > 	position: relative;
> > 	min-height: ${adSizes.billboard.height}px;
> > 	margin: 12px auto;
> > 
> > 	${from.desktop} {
> > 		margin: 0;
> > 		padding-bottom: 20px;
> > 	}
> > `;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I think the margin and padding [will be overridden](https://github.com/guardian/dotcom-rendering/blob/c4c6b382b145aaf8a03f90ee4d784d2ee4f5c825/dotcom-rendering/src/components/AdSlot.web.tsx#L154-L162) if the `.ad-slot--fluid` class is present.
> 
> I added your suggested change and I can always see in merch or merch-high this `.ad-slot--fluid` which like you said overrides the styling from `merchandisingAdStyles` because of the order of the css values. My question is how can we test that? I mean in which cases this change will be actually applied?

It should be applied when regular ads appear in the slot, the fluid class is only applied when the merch ads are inserted. Let me know if a call would be handy!

**Comment by deedeeh** [comment]
> > > > I think the margin should be on the slot to be consistent with fronts-banners? And only when a non-merch ad is present aka doesn't have the class `.ad-slot--fluid`
> > > 
> > > 
> > > Agreed, you can probably update the [`merchandisingAdStyles`](https://github.com/guardian/dotcom-rendering/blob/c4c6b382b145aaf8a03f90ee4d784d2ee4f5c825/dotcom-rendering/src/components/AdSlot.web.tsx#L204-L207) class to achieve this
> > > ```js
> > > const merchandisingAdStyles = css`
> > > 	position: relative;
> > > 	min-height: ${adSizes.billboard.height}px;
> > > 	margin: 12px auto;
> > > 
> > > 	${from.desktop} {
> > > 		margin: 0;
> > > 		padding-bottom: 20px;
> > > 	}
> > > `;
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I think the margin and padding [will be overridden](https://github.com/guardian/dotcom-rendering/blob/c4c6b382b145aaf8a03f90ee4d784d2ee4f5c825/dotcom-rendering/src/components/AdSlot.web.tsx#L154-L162) if the `.ad-slot--fluid` class is present.
> > 
> > 
> > I added your suggested change and I can always see in merch or merch-high this `.ad-slot--fluid` which like you said overrides the styling from `merchandisingAdStyles` because of the order of the css values. My question is how can we test that? I mean in which cases this change will be actually applied?
> 
> It should be applied when regular ads appear in the slot, the fluid class is only applied when the merch ads are inserted. Let me know if a call would be handy!

I am having a call with Simon at 12pm regarding this PR but if I need more clarification will ask you to join the call or send you a direct message. Thank you Jake!

**Review by SiAdcock — APPROVED** [review]

**Pull request merged**
