### PR TITLE
disables 'Shady Pie' for new product launch

### PR DESCRIPTION
**Pull request by michaelbjacobson**
## What does this change?
Disables 'Shady Pie' for new product launch, as authorised by by Marketing team.

### CODE REVIEW

**Review by mxdvl — APPROVED** [review]
Fine from our end. Is the plan to revert this once done?

**Review by emma-imber — APPROVED** [review]
You may need to tidy up the import variables in AdSlot (shouldHideReaderRevenue is no longer needed) but looks good otherwise!

**Comment by michaelbjacobson** [comment]
> Fine from our end. Is the plan to revert this once done?

I imagine the Shady Pie offer will need to be updated in-line with the new product, and then re-enabled, but I'm guessing it'll be disabled until the new product is fully rolled out.

**Comment by michaelbjacobson** [comment]
[Switch off "Shady Pie" on www.theguardian.com at V2 launch](https://trello.com/c/gjJrEJJh/675-switch-off-shady-pie-on-wwwtheguardiancom-at-v2-launch)

**Pull request merged**
