### PR TITLE
fix(fronts.yml): proper GHA syntax

### PR DESCRIPTION
**Pull request by mxdvl**
## What does this change?
Fix issues in the Github Actions.

## Why?
Because I messed up!

### CODE REVIEW

**Review by jlieb10 — APPROVED** [review]

**Comment by mxdvl** [comment]
Here’s a comment to edit.

**Comment by jlieb10** [comment]
⚡️ Lighthouse report for the changes in this PR:
| Category | Passed | Expected | Actual |
| --- | --- | --- | --- |
| Cumulative Layout Shift | ❌ | 0.002 | 0.004378350655237834 |
| Cumulative Layout Shift | ❌ | 0.002 | 0.0038219032287597657 |
 
🔥 2 of 2 audits failed.

**Comment by jlieb10** [comment]
⚡️ Lighthouse report for the changes in this PR:
| Category | Passed | Expected | Actual |
| --- | --- | --- | --- |
| Cumulative Layout Shift | ❌ | 0.002 | 0.004378350655237834 |
| Cumulative Layout Shift | ❌ | 0.002 | 0.0038219032287597657 |
 
🔥 2 of 2 audits failed.

**Comment by jlieb10** [comment]
⚡️ Lighthouse report for the changes in this PR:
| Category | Passed | Expected | Actual |
| --- | --- | --- | --- |
| Cumulative Layout Shift | ❌ | 0.002 | 0.004378350655237834 |
| Cumulative Layout Shift | ❌ | 0.002 | 0.0038219032287597657 |
 
🔥 2 of 2 audits failed.

**Pull request merged**
