### PR TITLE
Single front door AB test updates

### PR DESCRIPTION
**Pull request by marialani**
## What does this change?
Currently we only show the the "Subscriptions" link in the main navigation to supporters. For the duration of the Single Front Door AB Test we will display a "Print Subscriptions" link which isn't dependant on the user's supporter status and whether they're in the AB test. 

We will also hide the Supporter Revenue links in the footer for all users.

## Changes
- Hide Supporter Revenue links in the footer
- Update "Subscriptions" link in desktop navigation
- Update "Subscriptions" link in mobile navigation

These changes have been reproduced in frontend here: https://github.com/guardian/frontend/pull/24554

## Screenshots
| Before | After |
|-- | -- |
| Screenshot 2022-01-14 at 13 05 20 | Screenshot 2022-01-14 at 12 57 39 |
| Screenshot 2022-01-14 at 13 16 49 | Screenshot 2022-01-14 at 13 16 36 |

## Why
To support the new product proposition work we are going to run an AB test to measure the effect of replacing the current contribute/subscribe split messaging with a single 'support the guardian' call to action.

### CODE REVIEW

**Comment by marialani** [comment]
[🚪 Update "Subscriptions" link in www's DESKTOP navigation for "SingleFrontDoor" AB test](https://trello.com/c/mZdF04tD/220-%F0%9F%9A%AA-update-subscriptions-link-in-wwws-desktop-navigation-for-singlefrontdoor-ab-test)

**Comment by marialani** [comment]
[🚪 Update "Subscriptions" links in www's MOBILE navigation for duration of "SingleFrontDoor" AB test](https://trello.com/c/pPk0IBh0/222-%F0%9F%9A%AA-update-subscriptions-links-in-wwws-mobile-navigation-for-duration-of-singlefrontdoor-ab-test)

**Comment by marialani** [comment]
[🚪 Hide Supporter Revenue links in www's footer for "SingleFrontDoor" AB test](https://trello.com/c/mBkFqcfj/231-%F0%9F%9A%AA-hide-supporter-revenue-links-in-wwws-footer-for-singlefrontdoor-ab-test)

**Review by OllysCoding — APPROVED** [review]
+1

**Pull request merged**
