### PR TITLE
Fix core-js chunk duplication

### PR DESCRIPTION
**Pull request by arelra**
## What does this change?

@sndrs noticed we were heavily duplicating core-js in our webpack chunks.

I've traced this back to `polyfill-corejs3` being added to `babel.config` which I believe was added for #6562 .

## Why?

Fix size and performance regression

## Before and After

| Chunk | Type | Before | After | Reduction | ~% Reduction |
|--|--|--|--|--|--|
|all |parsed |2.42MB |**1.63MB** |0.79MB | 33% |
|all |gzip |903kB |**592kB** |311kB| 35% |

| Before      | After      |
|-------------|------------|
| ![before-chunks][] | ![after-chunks][] |
| ![before-stats][] | ![after-stats][] |

[before-chunks]: https://user-images.githubusercontent.com/7014230/213189804-8ceae745-3196-468e-98b4-f0f4f394bc4e.png
[after-chunks]: https://user-images.githubusercontent.com/7014230/213189955-693b09b9-172f-42c5-a0f1-2ec4de04630b.png

[before-stats]: https://user-images.githubusercontent.com/7014230/213190271-c598d1d1-ccdd-4581-b114-2cc46ceff547.png
[after-stats]: https://user-images.githubusercontent.com/7014230/213190374-d1c221e1-3530-4c4d-99f7-9039c0697a5d.png

## Next Steps

This is for the core team to agree on but I'd recommend:

- removing any non-production code that affect the build i.e. the recipe hack (sorry)
- better alerting of the build size and broken down into modern, variant and server
- upgrading Babel, plugins and preset-env
    - we should be able to drop most of the plugins as Babel supports ES2021 since v7.11
    - pick up any bugfixes and performance improvements
- the build size as reported on PRs has been steadily increasing over the last year so it might be worth a review of any new islands and dependencies being pulled in:
    | Date     | compressed-size-action MB |
    |----------|---------|
    | Jul 5th  | 1.55    |
    | Aug 4th  | 1.68    |
    | Oct 17   | 2.27    |
    | Jan 5th | 2.35    |
    | Now      | 2.98    |

## Related work

- we have a proposal to extract a vendor chunk  which should further improve deduplication and also rule out potential bugs from multiple instances of stateful libraries (e.g. preact, emotion and swr).

- we are still at the mercy of Webpack's default chunking strategy and how it chooses to duplicate modules - which we scupper by having multiple entry points on the same page. @sndrs has proposed we move to a single entry point.

### CODE REVIEW

**Comment by sndrs** [comment]
afaict, this removes _all_ of `core-js` from the bundle. is that what we'd expect?

**Comment by arelra** [comment]
> afaict, this removes _all_ of `core-js` from the bundle. is that what we'd expect?

I think so. It is reverting to the previous Babel setup before the core-js poyfill was added for a hack day project.

I think we only need core-js for syntax transforms and _not_ as polyfills as we use polyfill.io for that.

**Comment by sndrs** [comment]
> we don't need/want core-js for polyfills as we use polyfill.io for that

this sound right to me too. 

it does make me wonder how effective the current size reporting is - it seems we've been adding 187kb of unnecessary gzipped js to every page for a good while

would it be more useful to report total bundle sizes only (modern, legacy, variant)? does the build-based file breakdown give us anything?

**Review by OllysCoding — APPROVED** [review]
+1 Removing corejs pollyfills makes sense to me, as my understanding is that we use polyfill.io for this purpose

**Comment by arelra** [comment]
> would it be more useful to report total bundle sizes only (modern, legacy, variant)? does the build-based file breakdown give us anything?

Snap! Totally agree and I had already mentioned this in the 'next steps' section

**Review by mxdvl — APPROVED** [review]
This seems like the right approach. 

I was under the impression that the core-js plugin would not have resulted in polyfilling everything according to the env's targets. I only added it so I could use a feature that was not supported in our version of Node. I could have possibly noticed the bundle size increase but I had become numb to it as it had lots of false positives (small increases, falsly removed unnamed chunks) and negatives (new modules are not reported). A total bundle size for each of `modern`, `variant` and `legacy` would be a net improvement, but budgets should probably also be added.

**Pull request merged**
