### PR TITLE
Ensure Node versions are aligned

### PR DESCRIPTION
**Pull request by mxdvl**
## What does this change?

Compare node versions in `.nvmrc`, `riff-raff.yaml` and `Containerfile` to ensure that they are aligned.

## Why?

Helps with updates such as #7948 

## Left as an exercise to the reader

Implement a check for `@types/node` 😉

### CODE REVIEW

**Comment by sndrs** [comment]
would this work better as a commit hook that checks all those files if any of them appear in the list of changed files?

**Comment by sndrs** [comment]
> What’s the benefit of a commit hook over a CI check? Is it only about how quickly the developer is informed of the error? 

yes, basically. if we're going to check something, why wait until last possible moment to check it?

> Is there any risk that it could be disabled in certain contexts?

not really, you'd have to work quite hard to get round husky while still finding a way to install NPM packages.

that said, would it work better as part of `make validate`? `make lint-project` or something like that?

**Comment by mxdvl** [comment]
I appreciate the suggestions, but that would make Deno a hard requirement to commit on this codebase, which is not currently the case.

Considering that [at the current cadence LTS versions of Node are released at most once a year](https://github.com/nodejs/release#release-schedule) in late October, this proposal attempts to catch a bug which can only happen on very rare occasions. Ideally, I would leave further tweaks and refinements for @guardian/dotcom-platform to implement.

**Comment by mxdvl** [comment]
I implemented this quickly as a reaction to a chat thread that asked whether it would be technically feasible, but have little time to implement a different approach. If this PR is deemed unsatisfactory for any reason I’ll simply close it and let the team figure out a solution by end of April 2025.

> i reckon we could also get away with a regex check in all 3 files, that should be enough? that way we can remove the dependencies of the current deno script too

My aim here was to maximise safety by using a strongly-typed and fully parsed approach. The issues with alternatives are as follows:
- Node: need would need to add depdencies by add the parsing libraries to our `package.json`, giving them implicit acceptability–here that would be `zod`.
- Bash: I do not have enoug familiarity to produce something that behaves consistently
- Regular expressions: hard to maintain and would require a reimplementation of `SemVer` parsing, which is a solved problem

**Comment by mxdvl** [comment]
Closing in favour of an incoming pre-commit hook using a `RegExp`

**Pull request closed without merging**
