### PR TITLE
Make GetMatchTabs an island

### PR DESCRIPTION
**Pull request by ioannakok**
Co-authored-by: Oliver Lloyd <oliver.lloyd@freelancer.guardian.co.uk>
Co-authored-by: Joshua Lieberman <joshua.lieberman@guardian.co.uk>

## What does this change?
* Turning `GetMatchTabs` component to an `Island`.
* Fixes issue where match tabs were not showing in standard article.

## Why?
* Islands is our new hydration pattern

### Before
image

### After
image

### CODE REVIEW

**Review by oliverlloyd — APPROVED** [review]
Yep

**Comment by mxdvl** [comment]
Can someone explain to me how this fixed the missing tab issue?

**Comment by ioannakok** [comment]
> Can someone explain to me how this fixed the missing tab issue?

I had a look at this and actually that was not a prod issue at all, only a story issue. 
`HydratedLayout`: https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/src/web/layouts/Standard.stories.tsx#L259

calls `doStorybookHydration`
https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/src/web/browser/islands/doStorybookHydration.js

And since there was no `GetMatchTabs.importable.tsx`

**Comment by ioannakok** [comment]
As a side note, I realised the set up of the Standard/MatchReport story is a bit weird: https://www.chromatic.com/component?buildNumber=10431&historyLengthAtIndex=9&distanceToMoveBack=-4&appId=5dfcbf3012392c0020e7140b&name=Layouts%2FStandard&specName=MatchReport&componentInspectorKey=620fc019f033a3003af5ed41-1300-interactive-true. `MatchNav` and `MatchTabs` come from the Leicester - Arsenal match and the rest of the article body from the Swansea - Norwich. 

That is confusing: The Swansea - Norwich match report does not have MatchTabs because it does not have data in `minByMinUrl`. Condition to render MatchTabs here: https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/src/web/components/GetMatchTabs.importable.tsx#L26

Swansea - Norwich: https://www.theguardian.com/football/2021/feb/05/andre-ayew-sparks-swansea-victory-over-norwich-to-close-gap-at-top
Leicester - Arsenal: https://www.theguardian.com/football/2021/feb/28/leicester-arsenal-premier-league-match-report

**Comment by mxdvl** [comment]
🏝️  #3629

**Pull request merged**
