### PR TITLE
Check dependencies & node version on pull/merge

### PR DESCRIPTION
**Pull request by OllysCoding**
## What does this change?

Adds a 'post-merge' hook to git with husky:
1. If dependencies have been updated then run yarn to reinstall them
2. If the .nvmrc has changed, notify users to install the new version

I also deleted the apps-rendering `.nvmrc` which appears to be left over from the migration

## Why?

We've had intermittent issues with people having storybook or other dev tools not working because they've not updated dependencies, hopefully this will improve the developer experience!

This change emulates the existing post-merge hook with in [Frontend](https://github.com/guardian/frontend/blob/main/git-hooks/post-merge)

### CODE REVIEW

**Review by ioannakok — APPROVED** [review]
Nice one, Olly 👍

**Comment by OllysCoding** [comment]
[Check for new dependencies & node versions on pull/merge in DCR](https://trello.com/c/WL5VonH5/461-check-for-new-dependencies-node-versions-on-pull-merge-in-dcr)

**Comment by OllysCoding** [comment]
[Check for new dependencies & node versions on pull/merge in DCR](https://trello.com/c/WL5VonH5/461-check-for-new-dependencies-node-versions-on-pull-merge-in-dcr)

**Review by lucymonie — APPROVED** [review]
I love it!

**Pull request merged**
