### PR TITLE
New designs for `Analysis` and `Explainer` articles

### PR DESCRIPTION
**Pull request by alinaboghiu**
## What does this change?

This PR introduces the new designs for Analysis and Explainer articles. This is the main feature branch. Most of these changes were developed and reviewed on separate branches but this could also benefit from a final review.

## Why?

The Editorial Design team have created these new designs for Analysis and Explainer articles. the Journalism team have taken a week to implement these some of these changes in DCR and AR. 

https://docs.google.com/document/d/1MqSldxfgR86kOJaXTFNaBs5LzPzSa7jC4D4YwqqMFwg/edit#

## Screenshots

| Before      | After      |
|-------------|------------|
| ![beforeAnalysis][] | ![afterAnalysis][] |
| ![beforeExplainer][] | ![afterExplainer][] |

[beforeAnalysis]: https://user-images.githubusercontent.com/1229808/185647519-857357f5-2a4e-479e-8ad2-0808bd72b605.png
[afterAnalysis]: https://user-images.githubusercontent.com/1229808/185647549-a3df309a-93c0-4025-9d6f-b42b7513e391.png
[afterExplainer]: https://user-images.githubusercontent.com/1229808/186193753-2d5cca26-b8a0-479a-879c-10f1e5c2eef5.png
[beforeExplainer]: https://user-images.githubusercontent.com/1229808/186193762-1b80fb9c-d1ce-47d5-970d-f03a7c0963d4.png

### CODE REVIEW

**Comment by HarryFischer** [comment]
👍 This looks great!

**Review by oliverlloyd — APPROVED** [review]
This branch is mostly comprised of other pre-approved PRs so I'm approving here as it's unreasonable to expect others to review all these chagnes en mass

**Review by mxdvl — COMMENTED** [review]
Big piece of work 👏 

I’m not sure I understand why an `Analysis` with [`SpecialReport`](https://5dfcbf3012392c0020e7140b-siyfjsmhsp.chromatic.com/?path=/story/components-layout-format-variations--standard-analysis-special-report-theme) or [`Labs`](https://5dfcbf3012392c0020e7140b-siyfjsmhsp.chromatic.com/?path=/story/components-layout-format-variations--standard-analysis-labs) gets a theme-specific colour, but the other pillars like [`Sport`](https://5dfcbf3012392c0020e7140b-siyfjsmhsp.chromatic.com/?path=/story/components-layout-format-variations--standard-analysis-sport) and [`Culture`](https://5dfcbf3012392c0020e7140b-siyfjsmhsp.chromatic.com/?path=/story/components-layout-format-variations--standard-analysis-culture) do not. Same question for `Explainer`, which is only red, black or teal.

**Comment by alinaboghiu** [comment]
@mxdvl I think this is because the SpecialReport and Labs themes are, well, special. Unfortunately there are no explicit designs for these yet as we aren't required to support these combinations. So we just made an educated guess as to which themes should win - in other cases SpecialReport and Labs win over other themes so we maintained this pattern.

**Pull request merged**
