### PR TITLE
chore: replace --static-dir CLI flag with staticDirs for storybook commands

### PR DESCRIPTION
**Pull request by jamesgorrie**
The [CLI flag is deprecated](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated---static-dir-cli-flag), so this will help when we want to update storybook.

## Screenshots

Icons still working, which are pulled in from `/src/static`.
screenshot of card with video icon rendering

### CODE REVIEW

**Review by mxdvl — APPROVED** [review]
Yes please!

**Review by OllysCoding — APPROVED** [review]
+1 Nice :)

**Review by AshCorr — APPROVED** [review]
Awesome :)

**Comment by AshCorr** [comment]
We still want this!

**Comment by mxdvl** [comment]
If this is still good, can we get in in, @jamesgorrie ?

**Pull request closed without merging**
