### PR TITLE
Remove common-rendering

### PR DESCRIPTION
**Pull request by joecowton1**
## What does this change?

Removes common-rendering, the common-rendering Chromatic github workflow, and all references to common-rendering.

## Why?

It's no longer required.

### CODE REVIEW

**Review by AshCorr — APPROVED** [review]
Woohoo!

**Comment by mxdvl** [comment]
FYI this broke the `peer-dependencies` Deno script.

This was not flagged possible because:
- we don’t type-check or format the deno scripts on pull requests
- these scripts are only run at specific intervals

**Comment by joecowton1** [comment]
> * we don’t type-check or format the deno scripts on pull requests

Is there a reason not to do this?

**Comment by mxdvl** [comment]
This PR is fine, but I have opened an issue to fix scripts: #7175

**Comment by sndrs** [comment]
> FYI this broke the `peer-dependencies` Deno script.
> 
> This was not flagged possible because:
> 
> * we don’t type-check or format the deno scripts on pull requests
> * these scripts are only run at specific intervals

this feels like an inherent flakiness from running things as deno scripts – or rather, from having multiple, ad hoc ways of doing things.

if deno is how we want to run scripts in a repo, it should be a first class citizen (and probably the only way to do it). having multiple ways, with different degrees of 'official' support/integration is hard to scale – this might be a good example

i think it's a lot to ask of people who don't work on a codebase all day long to know that these niches exist

**Comment by mxdvl** [comment]
> this feels like an inherent flakiness from […] having multiple, ad hoc ways of doing things.

Absolutely! These scripts are not essential, and the cost of flakiness was and remains a lot lower than spinning up a new yarn workspace specifically for things that should only run in CI… hence the choice of a different JS runtime–Deno.

**Pull request merged**
