### PR TITLE
Explicit list of Formats to test on Layouts and Cards in Chromatic

### PR DESCRIPTION
**Pull request by jamesgorrie**
Co-authored-by: 77005274+joecowton1@users.noreply.github.com

## What does this change?

Creates an explicit list for layouts and cards that we generate for Storybook & Chromatic.

We'd like to investigate whether this :
* reduces the amount of snapshots run over a month in Chromatic
* reduces cognitive load when a change affects all files in the Chromatic diff
* increases the amount of bugs released

This expects engineers to explicitly add formats that we care about.

This is a discussion point around trying to simplify our storybook, reduce our cost on Chromatic but not reduce useful coverage.

### CODE REVIEW

**Comment by bryophyta** [comment]
Explicit and declarative -- this looks good to me!

Not quite clear whether this is a PR or an RFC (given your comment in the chat). If it's a PR, though, I feel as though we should at least have some inline comments explaining how `testLayoutFormats` is intended to be used?

And it would also be good to add mention of this to our docs (maybe that's a separate PR though?)

**Comment by jamesgorrie** [comment]
@bryophyta 

> whether this is a PR or an RFC

It's a PR - discussion encouraged though!

>  I feel as though we should at least have some inline comments explaining how `testLayoutFormats` is intended to be used?

What's your reading in how it should be used?

**Comment by bryophyta** [comment]
> What's your reading in how it should be used?

That's a good question! I guess my main thought is that before we were aiming for the generated stories to have total coverage across the possible formats (?) whereas now they need to be manually specified, but still automatically generated. Meaning that devs might need to go into the `scripts/` folder for a task (adding a specific story) that they didn't need to before.

Having thought about it, I wonder whether having the documentation in the storybook itself might be the most useful thing here? e.g. something like [this branch](https://github.com/guardian/dotcom-rendering/compare/disable-gen-stories...disable-gen-stories-pf-readme?expand=1) -- probably needs some work but I thought it was best not to sink too much time into it in case we don't like that pattern

**Comment by jamesgorrie** [comment]
@bryophyta the reason to define the format and use the loop is so that we can add stories quickly without copy/pasting the whole block as the code was already written to support this. This is to support adding any new ones going forward.

If we find this coverage altogether not useful, we can remove it fully. My question is still very much around what coverage this gives us and what does it help us stop releasing?

I am more than happy to look into documenting it, probably from a starting point, if we find out what this is good for.

e.g.

Creating a new layout? Add a layout test.

**Comment by bryophyta** [comment]
@jamesgorrie thanks, that makes sense to me!

As mentioned in my comment above, if we do want to add some documentation, putting it in the storybook itself might be a good option. PR #6783 provides a template for doing so. Understandable if we want to wait until we have a better understanding of _what_ to document, as you suggest. But just highlighting it here to avoid having to re-implement if we decide to do it like that

**Review by bryophyta — APPROVED** [review]

**Comment by jamesgorrie** [comment]
@bryophyta 
> wait until we have a better understanding of what to document, as you suggest.

This is exactly what I was trying to say!

**Comment by mxdvl** [comment]
I think that it would be nice to have real articles that match the variations that we expect… if there’s probably a lot of variations that do not really make any sense!

Maybe the script that generates the variation could dynamically fetch data real articles, so what we store is simply URLs?
That means that for an article to make its way into our visual testing, it needs to be something we actually care about supporting.

**Comment by jamesgorrie** [comment]
@mxdvl 

>  real articles that match the variations that we expect

Pretty much reflecting what @joecowton1, DevX and I have been talking about. We need to share these conversations more widely especially around when to use Chromatic for future engineers.

> Fetch data real articles

This could be interesting - probably store the responses locally like we do on `frontend`. But would a tool like Percy make more sense? We're probably going to set up a session with Chromatic to help us with this.

**Pull request merged**
