### PR TITLE
Special Background

### PR DESCRIPTION
**Pull request by oliverlloyd**
## What does this change?
Adds a greyish hue to the page background for `Special.SpecialReport` (except for `Comment` pieces, which remain peach)

## Standard
Screenshot 2021-01-27 at 10 21 12

## Showcase
Screenshot 2021-01-27 at 10 22 59

## Comment
Screenshot 2021-01-28 at 12 39 49

## Immersive
Screenshot 2021-01-27 at 10 20 21

### An extra div for Immersives
In order to correctly set the background alongside the immersive headline without falling foul of z-index issues, I had to create a new wrapper div for these header elements

### CODE REVIEW

**Review by nitro-marky — APPROVED** [review]
The future...

**Review by liywjl — APPROVED** [review]
👍

**Comment by oliverlloyd** [comment]
@HarryFischer What should be the background colour for a Special Report comment piece?

See: https://www.theguardian.com/commentisfree/2016/apr/05/iceland-crisis-2009-offshore-sigmundur-david-gunnlaugsson-panama-papers

This piece on Frontend has the dark grey pillar colour for things like the dropcap and meta from SpecialReport but keeps the peach background from the comment tone.

**Comment by oliverlloyd** [comment]
As per discussions offline with @HarryFischer I've amended this PR to keep the `opinion[800]` with `Design.Comment`, even if the `Theme.SpecialReport` is set.

**Pull request merged**
