### PR TITLE
Use @guardian/prettier config

### PR DESCRIPTION
**Pull request by sndrs**
## What does this change?

adds [@guardian/prettier](https://www.npmjs.com/package/@guardian/prettier) and applies the config

## Why?

standardisation 

## Reviewing

there's a lot of changes but apart from install the config, the came from running `make fix`, and are whitespace-only. 

if you [ignore whitespace changes](https://github.com/guardian/dotcom-rendering/pull/2267/files?diff=unified&w=1), it's basically just adding the config.

### CODE REVIEW

**Comment by sndrs** [comment]
I thought this would be simple, but there's a lot of rules in conflict with each other I think. closing for another day

**Review by liywjl — APPROVED** [review]
When removing whitespace changes, only 3 files diffed :) LGTM

**Comment by gtrufitt** [comment]
> I thought this would be simple, but there's a lot of rules in conflict with each other I think. closing for another day

I updated the JSX indent rules in eslint (we were using spaces, prettier default and guardian default is tabs):

```
'react/jsx-indent': [2, 'tab'],
'react/jsx-indent-props': [2, 'tab'],
```

Passes eslint locally, hopefully here too!

**Review by oliverlloyd — APPROVED** [review]
We shold get this one in fast to avoid more conflicts!

**Comment by sndrs** [comment]
oh nice one @gtrufitt – I'll look at adding a proper react ESLint config too to the guardian ones

**Review by gtrufitt — APPROVED** [review]
go go pretty code

**Review by shtukas — APPROVED** [review]

**Review by oliverlloyd — APPROVED** [review]
So pretty

**Pull request merged**
