### PR TITLE
Use VideoAtom in DCR

### PR DESCRIPTION
**Pull request by oliverlloyd**
With this PR, if DCR is sent:

```typescript
interface MediaAtomBlockElement {
    _type: 'model.dotcomrendering.pageElements.MediaAtomBlockElement';
    id: string;
    assets: VideoAssets[];
    posterImage?: {
        url: string;
        width: number;
    }[];
    title?: string;
    duration?: number;
}
```

then it will

```typescript
                case 'model.dotcomrendering.pageElements.MediaAtomBlockElement':
                    return (
                        <VideoAtom
                            assets={element.assets}
                            poster={
                                element.posterImage &&
                                element.posterImage[0].url
                            }
                        />
                    );
```

See: https://github.com/guardian/atoms-rendering/pull/109

### CODE REVIEW

**Comment by oliverlloyd** [comment]
[Support non-Youtube (media atom) video](https://trello.com/c/tqlZ6kRw/2117-support-non-youtube-media-atom-video)

**Comment by gtrufitt** [comment]
I have a slight concern with the use of `MediaAtomBlockElement` which is more of a tidy-up job outside of this PR but the internal terminology of `Media Atom` will suggest to most people what we've called `YoutubeBlockElement`. I think probably we need to call *both* Media atom - one MediaAtomNonYoutube and MediaAtomYoutube or something so that we're a bit clearer. cc/ @jfsoul @shtukas

**Review by liywjl — APPROVED** [review]

**Review by gtrufitt — APPROVED** [review]

**Comment by jfsoul** [comment]
@gtrufitt yes I agree a review of the naming might be worthwhile, I still find it a bit confusing as someone who casually dips into the code without spending much time actually working on it.

**Comment by oliverlloyd** [comment]
Re, naming. I completely agree. But it's not just here, all of the components around videos are confusingly named!

+1 for a comprehensive review

**Comment by oliverlloyd** [comment]
I've added https://trello.com/c/OmM3PmDE/2158-review-video-naming-conventions to capture the naming review work

**Pull request merged**
