### PR TITLE
eslint

### PR DESCRIPTION
**Pull request by AWare**
## What does this change?
How about we used eslint instead of #159 ?

### CODE REVIEW

**Comment by AWare** [comment]
I haven't figured out how to make it look at tsx, ts and js files yet.

**Comment by SiAdcock** [comment]
I think in the [makefile](https://github.com/guardian/dotcom-rendering/blob/master/makefile#L72) you'll need to tell ESLint to [look for those extensions](https://eslint.org/docs/user-guide/command-line-interface#options) using `--ext .ts,.tsx,.js`

**Comment by AWare** [comment]
I'm getting a lot of `no-undef` for type definitions.

**Comment by SiAdcock** [comment]
`no-undef` is [not an applicable linting rule](https://github.com/buzinas/tslint-eslint-rules#variables) since TypeScript compiler errors if you reference an undefined variable. The workaround is to [disable the rule](https://github.com/eslint/typescript-eslint-parser/issues/416#issuecomment-363115171) on TypeScript files.

**Comment by AWare** [comment]
I would really have expected either the plugin or the parser to have automated/documented this. (Also the extensions)

**Comment by SiAdcock** [comment]
Yeah, I'd say it's more the plugin's responsibility. I think there's a question mark hanging over how well maintained the plugin is.

**Comment by AWare** [comment]
https://github.com/nzakas/eslint-plugin-typescript/issues/33  
https://github.com/wmonk/create-react-app-typescript/pull/354

**Comment by AWare** [comment]
alas poor eslint

**Pull request closed without merging**
