### PR TITLE
Enable Enhanced Privacy Mode for Youtube AMP Component

### PR DESCRIPTION
**Pull request by frj**
This PR enables 'Enhanced Privacy Mode' in the Youtube AMP Component.

This is the AMP equivalent of using the youtuble-nocookie.com domain for Youtube iframe embeds, essentially disabling cookies and the tracking of users by Youtube via content embedded on AMP pages.

For more details see the AMP documentation:

https://amp.dev/documentation/components/amp-youtube/  

### Before
Screenshot 2020-12-02 at 10 42 00

### After
Screenshot 2020-12-02 at 10 40 59

## Why?

This is to improve the privacy of users viewing Guardian content with embedded Youtube videos.

### CODE REVIEW

**Review by oliverlloyd — APPROVED** [review]
This is great!

I know there's been some work recently around amp validation @jfsoul is this active now or are there additional steps needed to check this branch?

**Comment by oliverlloyd** [comment]
In fact, would it be possible to port the AMP checks into a Github Action to expose them better?

**Comment by oliverlloyd** [comment]
The BBC have a [nice example](https://github.com/bbc/simorgh/blob/latest/scripts/ampHtmlValidator/index.js) of amp validation checks [happening inline](https://github.com/bbc/simorgh/blob/latest/.github/workflows/simorgh-local-server-tests.yml#L37)

**Comment by frj** [comment]
[Do Not Track - YouTube AMP](https://trello.com/c/6rxEVtnV/2202-do-not-track-youtube-amp)

**Review by oliverlloyd — APPROVED** [review]

**Pull request merged**
