### PR TITLE
Use minimum that's a multiple of 3

### PR DESCRIPTION
**Pull request by jfsoul**
## What does this change?
Changes our ASG min size to 9 from 8 so that we always have balance between the 3 AZs.

## Why?
There have been occasional issues when deploys happen very close together that we have attributed to automatic rebalancing done by AWS (that they have confirmed can't be controlled by us).

### CODE REVIEW

**Review by liywjl — APPROVED** [review]
👍

**Review by shtukas — APPROVED** [review]

**Comment by shtukas** [comment]
Interesting 🤔

**Comment by nicl** [comment]
Worth checking the instance type and CPU credits monitoring as for some of the burstable instances even a lowish CPU can indicate exceeding the burst credits and end up costing more than you want.

**Comment by jfsoul** [comment]
Thanks @nicl that's a great point. Every time I come back to these instances I forget that 🤦, but it is absolutely the case here. Based on previous experience I am now thinking we should go to 9 instead of 6.

**Pull request merged**
