### PR TITLE
Import Lines from the development kitchen 🍳 

### PR DESCRIPTION
**Pull request by jamie-lynch**
## What does this change?

This PR updates both apps-rendering and dotcom-rendering to import the lines component from [@guardian/source-react-components-development-kitchen](https://www.npmjs.com/package/@guardian/source-react-components-development-kitchen) instead of [@guardian/src-ed-lines](https://www.npmjs.com/package/@guardian/src-ed-lines).

## Why?

Following https://github.com/guardian/source/pull/963, editorial components are now exported from the new [@guardian/source-react-components-development-kitchen](https://www.npmjs.com/package/@guardian/source-react-components-development-kitchen) package and [@guardian/src-ed-lines](https://www.npmjs.com/package/@guardian/src-ed-lines) is deprecated.

cc @guardian/client-side-infra

### CODE REVIEW

**Comment by oliverlloyd** [comment]
> **Size Change:** +16.4 kB (+2%)
> 
> `dist/frontend.server.js`	321 kB	+27.5 kB (+9%)	🔍

Is this change really adding 16kB to the page?

**Comment by oliverlloyd** [comment]
> > **Size Change:** +16.4 kB (+2%)
> > `dist/frontend.server.js`	321 kB	+27.5 kB (+9%)	🔍
> 
> Is this change really adding 16kB to the page?

Is this related to how we're importing the whole kitchen vs. just `Lines`?

Screenshot 2021-09-20 at 16 40 34
vs.
Screenshot 2021-09-20 at 16 41 01

**Comment by jamie-lynch** [comment]
> Is this related to how we're importing the whole kitchen vs. just `Lines`?

Quite possibly. I meant to callout that I had to add `@guardian/src-brand` to DCR to stop a couple of tests failing. It's a peerDependency of `source-react-components-development-kitchen` because of the `Logo` component but I can't see that being used anywhere in DCR. 

@SiAdcock @sndrs something that we might need to have a think about

**Comment by sndrs** [comment]
this stuff should be being tree-shaken – we should look at why it's not

**Comment by jamie-lynch** [comment]
@oliverlloyd @sndrs I've updated this to use a new prerelease of the development kitchen with the `sideEffects` value set to false in the `package.json` (https://github.com/guardian/source/pull/990) and that seems to have sorted it.

> Size Change: -7.05 kB (-1%)

Assuming that this is all good, I guess we publish a non-rc version of the kitchen and then bump this again before it gets merged.

**Review by JamieB-gu — COMMENTED** [review]
Nice! LGTM

**Review by idrise — APPROVED** [review]

**Review by nitro-marky — APPROVED** [review]
LGTM

**Review by oliverlloyd — APPROVED** [review]
These types of PRs are sooo satisfying

**Review by OllysCoding — APPROVED** [review]

**Pull request merged**
