### PR TITLE
Show full navigation menu on top of top-above-nav slot

### PR DESCRIPTION
**Pull request by ioanna0**
## What does this change?

On tablets the navigation menu was hidden behind top-above-nav ad slot. Changes top above nav z-index so that the navigation menu appears on top of it.
Also reducing right margin to make the menu larger and meet the burger button as in DCP

### Before

Screenshot 2021-01-11 at 15 14 49

### After

Screenshot 2021-01-11 at 20 39 03

### DCP for reference:

**Note to dotcom team: Another card might be needed to give the same menu overlay as in DCP** 

Screenshot 2021-01-11 at 20 39 12

## Why?
Will give full visibility of navigation menu on tablets

### CODE REVIEW

**Comment by gtrufitt** [comment]
I have a feeling this may cause issues on desktop with the positioning of the sticky ad over the nav being what you want on desktop?

**Comment by ioanna0** [comment]
> I have a feeling this may cause issues on desktop with the positioning of the sticky ad over the nav being what you want on desktop?

@gtrufitt I don't see any impact on desktop on top-above nav or on the right hand sticky ad, are you referring to something else?
Screenshot 2021-01-12 at 13 52 02

**Review by liywjl — APPROVED** [review]
Looks good, seems to fix the top above Ad issue 👍 

We may need to do some work with the burger button as it doesnt seem to aline correctly, ill add a task for that

**Comment by gtrufitt** [comment]
> @gtrufitt I don't see any impact on desktop on top-above nav or on the right hand sticky ad, are you referring to something else?

This is what I was thinking yes, I'm just surprised as the sticky ad and the header z-indexes are tightly coupled to enable to sticky ad to be above and this seems to invert that behaviour... 

If nothing else, we'll need to review the naming here: https://github.com/guardian/dotcom-rendering/blob/main/src/web/layouts/lib/stickiness.tsx#L47

cc/ @oliverlloyd

**Comment by ashishpuliyel** [comment]
@ioanna0 Looks good to me. I've accepted the chromatic changes which were all false-positives.

**Comment by ioanna0** [comment]
@gtrufitt You were right, there was a use case I haven't check which was when scrolling the z-index previously was higher and thus giving a sticky effect so I have reverted this PR for now https://github.com/guardian/dotcom-rendering/pull/2364

Will need to reconsider a fix for this

**Pull request merged**
