### PR TITLE
Lock accessibility score at 96

### PR DESCRIPTION
**Pull request by jorgeazevedo**
## What does this change?

This will make the lighthouse action and lighthouse status check fail if the accessibility goes above or below 96.

When that happens, the result will be

### After

The action fails
Lock_accessibility_score_at_96_by_jorgeazevedo_·_Pull_Request__3_·_jorgeazevedo_dotcom-rendering

The status check
Lock_accessibility_score_at_96_by_jorgeazevedo_·_Pull_Request__3_·_jorgeazevedo_dotcom-rendering

Wish the error was more descriptive (like "This PR introduces one new accessibility issue")  but I don't think it's configurable or anything :-\

## Why?

This will hopefully prevent us from introducing accessibility issues on the article page (the ones lighthouse can detect, anyway).

If the score goes up, we still get a failure. The PR author will need to bump the accessibility score assertion value, and gets to brag about it in standup the next day.

### CODE REVIEW

**Review by nicl — APPROVED** [review]
Nice!

**Comment by oliverlloyd** [comment]
@jorgeazevedo is this PR good to merge?

**Comment by jorgeazevedo** [comment]
oh my god I could have sworn I merged this!! Score is still 96 on main so I think we're good, but still major 🤦‍♂️ I'll fix the conflicts and merge, thanks so much for flagging this!

**Review by liywjl — APPROVED** [review]
LGTM 👍

**Comment by liywjl** [comment]
Unusual that it is failing, as it looks like accessibility is 96
Screenshot 2020-11-19 at 10 12 13

**Comment by jorgeazevedo** [comment]
yeah @liywjl !! It says an assertion failed

Lock_accessibility_score_at_96_by_jorgeazevedo_·_Pull_Request__1895_·_guardian_dotcom-rendering

But I'm looking at the console output and the assertions are all green!!

Lock_accessibility_score_at_96_by_jorgeazevedo_·_Pull_Request__1895_·_guardian_dotcom-rendering

Like whaaat?? I'll see if I can find a few minutes this afternoon to figure out what the hell is going on before I merge

**Comment by oliverlloyd** [comment]
@jorgeazevedo  I see there's a [new version of lighthouse](https://github.com/GoogleChrome/lighthouse-ci/compare/v0.6.1...v0.7.0) now, maybe that helps with the issues here?

**Comment by jorgeazevedo** [comment]
@oliverlloyd finally got this to work. Yes - new version of lhci fixes the assertion problem. For some reason the github token used to post the results changed and it was failing to post the report back to the PR.

Accessibility isn't at 96 anymore :-\ dropped to 87 https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1614966932733-40174.report.html#accessibility

This seems new. Might be a regression, or something that's being picked up by the new version of lhci

Lighthouse_Report

**Comment by gtrufitt** [comment]
Hoping that the a11y fixes as a part of this PR now mean we are `gt` 96 and can merge this!

**Pull request merged**
