### PR TITLE
More verbose sentry logs for consent errors

### PR DESCRIPTION
**Pull request by ioanna0**
## What does this change?
Bumps CMP lib to latest, which adds some more detailed error logging to help debugging consent errors in DCR.
Also added the [`CaptureConsole` integration](https://docs.sentry.io/platforms/javascript/configuration/integrations/plugin/#captureconsole) plugin in Sentry configuration so that we can see the console logs in sentry.
 
### Before

N/A

### After
N/A

## Why?

Will help debugging consent errors in DCR

### CODE REVIEW

**Review by oliverlloyd — APPROVED** [review]
Nice. I'm very curious how this extra console informaiton will look - this could really help with solving problems.

**Review by mxdvl — APPROVED** [review]
Great!

**Review by liywjl — APPROVED** [review]
👍

**Comment by ioanna0** [comment]
@oliverlloyd Yeah let's see how it shows in sentry with just the `error` level and we can add more log levels to capture all different console messages

**Pull request merged**
