### PR TITLE
Use img tag instead of picture

### PR DESCRIPTION
**Pull request by oliverlloyd**
## What?
This PR proposes replacing the [picture](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture) tag with an [img](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Img) tag as a stopgap ahead of using [image-rendering](https://github.com/guardian/image-rendering)

## TLDR
Surprisingly, tests for this change showed a lot of deviation between Frontend vs. DCR, both DCR with a picture tag and DCR with an img tab. More surprisingly, DCR with an img tag often outperformed Frontend. These variations could be for a lot of reasons though, not purely because an `img` tag was used.

## How?
There are two main code changes here:

1. Moving all image manipulation related logic into the `Picture` (now called `Img`) component
2. Removing the `hdipi` related logic and adding the ability to create sizes.

## Why?
DCR has known issues where it can sometimes render substantially lower quality images than appropriate in the context of position, screen width and resolution. In the short term, this change brings us into line with Frontend in most cases, makes us actually do better than frontend in some cases, and leaves us at the same or an acceptable level below frontend in the rest. 

## Why is this a stopgap?
See this [ongoing discussion](https://docs.google.com/document/d/1LfSCS0e9KJFxQuehguEdYdbns_afDSrtxx8MI9zgiMg/edit#heading=h.w4spq6y4l65b) for more detail on our medium to longer term goals. But to summarise we want to:

1. Solve the [Wealthy Guy problem](https://github.com/guardian/frontend/pull/11400). Mobile devices with small screens but high dpr values can end up being served excessively large files, wasting bandwidth.

2. [Finesse the quality](https://blog.imgix.com/2016/03/30/dpr-quality). We want to be able to specify a different set of images to use above a certain resolution. This is because we've found that for high resolution screens, by using `dpr=2&quality=45` together we can reduce the file size without noticeably impacting quality.

Both of these need a `picture` tag based solution.

## Test methodology
I rendered different images using a variety of simulated devices (via Firefox and Chrome dev tools) and then checked the resulting src chosen by the browser. Test were done using code from Frontend, new DCR and current DCR.

### Example urls:
https://www.theguardian.com/artanddesign/2020/may/11/cross-border-love-a-photo-essay?dcr=false
http://localhost:3030/Article?url=https://www.theguardian.com/artanddesign/2020/may/11/cross-border-love-a-photo-essay
https://www.theguardian.com/artanddesign/2020/may/11/cross-border-love-a-photo-essay?dcr=true

#### Desktop DPR 2
_immersive_
Frontend: [`width=1300` | `quality=45` | `dpr=2`](https://i.guim.co.uk/img/media/c3f2b5be3c0ff0a509fcce198ea36a40b79473fa/0_0_5025_3524/master/5025.jpg?width=1300&quality=45&auto=format&fit=max&dpr=2&s=5c1329b4620e53bf5744a6a00a7beb4f) 
New DCR: [`width=1300` | `quality=45` | `dpr=2`](https://i.guim.co.uk/img/media/c3f2b5be3c0ff0a509fcce198ea36a40b79473fa/0_0_5025_3524/master/5025.jpg?width=1300&quality=45&auto=format&fit=max&dpr=2&s=5c1329b4620e53bf5744a6a00a7beb4f) 
Current DCR: [`width=1300` | `quality=85`](https://i.guim.co.uk/img/media/c3f2b5be3c0ff0a509fcce198ea36a40b79473fa/0_0_5025_3524/master/5025.jpg?width=1300&quality=85&auto=format&fit=max&s=194cce5fe2bb0473fd3afc5f748a4d20) 

_showcase (main media 1020 pixels)_
Frontend: [`width=1300` | `quality=45` | `dpr=2`](https://i.guim.co.uk/img/media/074610db5868e442eae504454a724e6328dcdd38/0_341_8485_5091/master/8485.jpg?width=1300&quality=45&auto=format&fit=max&dpr=2&s=9b9896344ef1a71d5f2be68ed164a63e)
New DCR: [`width=1020` | `quality=45` | `dpr=2`](https://i.guim.co.uk/img/media/074610db5868e442eae504454a724e6328dcdd38/0_341_8485_5091/master/8485.jpg?width=1020&quality=45&auto=format&fit=max&dpr=2&s=dca3ef83633276c8c89f9244d396c22a)
Current DCR: [`width=1020` | `quality=85`](https://i.guim.co.uk/img/media/074610db5868e442eae504454a724e6328dcdd38/0_341_8485_5091/master/8485.jpg?width=1020&quality=85&auto=format&fit=max&s=0264ad41e0f53b3aaf2968e6f8b96e11)

_inline_
Frontend: [`width=620` | `quality=45` | `dpr=2`](https://i.guim.co.uk/img/media/833c4a3c34e8d98bcdde9c061e4e51630fac4cf5/0_174_3920_5215/master/3920.jpg?width=620&quality=45&auto=format&fit=max&dpr=2&s=5a993ef5e2aec4e7412ca928e00e2e18) 
New DCR: [`width=620` | `quality=45` | `dpr=2`](https://i.guim.co.uk/img/media/833c4a3c34e8d98bcdde9c061e4e51630fac4cf5/0_174_3920_5215/master/3920.jpg?width=620&quality=45&auto=format&fit=max&dpr=2&s=5a993ef5e2aec4e7412ca928e00e2e18) 
Current DCR: [`width=620` | `quality=85`](https://i.guim.co.uk/img/media/833c4a3c34e8d98bcdde9c061e4e51630fac4cf5/0_174_3920_5215/master/3920.jpg?width=620&quality=85&auto=format&fit=max&s=cd561472fc59eba2e32081ecc1a1ba7c) 

_showcase (860 pixels wide)_
Frontend: [`width=880` | `quality=45` | `dpr=2`](https://i.guim.co.uk/img/media/fdf8646d4fe55f7019ee8e5ccc822fc1e4aecaba/0_0_5876_3917/master/5876.jpg?width=880&quality=45&auto=format&fit=max&dpr=2&s=e4417c91e4c1e2442a762b462d615889) 
New DCR: [`width=940` | `quality=45` | `dpr=2`](https://i.guim.co.uk/img/media/fdf8646d4fe55f7019ee8e5ccc822fc1e4aecaba/0_0_5876_3917/master/5876.jpg?width=940&quality=45&auto=format&fit=max&dpr=2&s=1ce667943371caeb5715d65c83156bcd) 
Current DCR: [`width=1020` | `quality=85`](https://i.guim.co.uk/img/media/fdf8646d4fe55f7019ee8e5ccc822fc1e4aecaba/0_0_5876_3917/master/5876.jpg?width=1020&quality=85&auto=format&fit=max&s=664f02bd4ba9aeeb50cf0c066fb10e13) 

_thumbnail_
Frontend: [`width=140` | `quality=45` | `dpr=2`](https://i.guim.co.uk/img/media/220567fcc8d219a96815fc9754f9c6beb6e87f61/874_8_1478_1478/master/1478.jpg?width=140&quality=45&auto=format&fit=max&dpr=2&s=69c9988b7b919bd8d34035e4122127d9) 
New DCR: [`width=140` | `quality=45` | `dpr=2`](https://i.guim.co.uk/img/media/220567fcc8d219a96815fc9754f9c6beb6e87f61/874_8_1478_1478/master/1478.jpg?width=140&quality=45&auto=format&fit=max&dpr=2&s=69c9988b7b919bd8d34035e4122127d9) 
Current DCR: [`width=140` | `quality=85`](https://i.guim.co.uk/img/media/220567fcc8d219a96815fc9754f9c6beb6e87f61/874_8_1478_1478/master/1478.jpg?width=140&quality=85&auto=format&fit=max&s=41fe0132802e7dab3320352ab19da0a9) 

#### Desktop DPR 1
_inline_
Frontend: [`width=620` | `quality=85`](https://i.guim.co.uk/img/media/833c4a3c34e8d98bcdde9c061e4e51630fac4cf5/0_174_3920_5215/master/3920.jpg?width=620&quality=85&auto=format&fit=max&s=cd561472fc59eba2e32081ecc1a1ba7c) 
New DCR: [`width=620` | `quality=85`](https://i.guim.co.uk/img/media/833c4a3c34e8d98bcdde9c061e4e51630fac4cf5/0_174_3920_5215/master/3920.jpg?width=620&quality=85&auto=format&fit=max&s=cd561472fc59eba2e32081ecc1a1ba7c) 
Current DCR: [`width=620` | `quality=85`](https://i.guim.co.uk/img/media/833c4a3c34e8d98bcdde9c061e4e51630fac4cf5/0_174_3920_5215/master/3920.jpg?width=620&quality=85&auto=format&fit=max&s=cd561472fc59eba2e32081ecc1a1ba7c) 

#### iphone (375 pixels wide)
_inline_
Frontend: [`width=300` | `quality=85`](https://i.guim.co.uk/img/media/833c4a3c34e8d98bcdde9c061e4e51630fac4cf5/0_174_3920_5215/master/3920.jpg?width=300&quality=85&auto=format&fit=max&s=17c6dc225e8a3fe3bb901d977f2bccd1) 
New DCR: [`width=445` | `quality=85`](https://i.guim.co.uk/img/media/833c4a3c34e8d98bcdde9c061e4e51630fac4cf5/0_174_3920_5215/master/3920.jpg?width=445&quality=85&auto=format&fit=max&s=66e91635408beb4994da3a22e246049c) 
Current DCR: [`width=445` | `quality=85`](https://i.guim.co.uk/img/media/833c4a3c34e8d98bcdde9c061e4e51630fac4cf5/0_174_3920_5215/master/3920.jpg?width=445&quality=85&auto=format&fit=max&s=66e91635408beb4994da3a22e246049c) 

_immersive_
Frontend: [`width=300` | `quality=85`](https://i.guim.co.uk/img/media/c3f2b5be3c0ff0a509fcce198ea36a40b79473fa/0_0_5025_3524/master/5025.jpg?width=300&quality=85&auto=format&fit=max&s=e64a5688b116b54310f1391f305b1b61) 
New DCR: [`width=465` | `quality=85`](https://i.guim.co.uk/img/media/c3f2b5be3c0ff0a509fcce198ea36a40b79473fa/0_0_5025_3524/master/5025.jpg?width=465&quality=85&auto=format&fit=max&s=a98ec652f09be8e6e8f2bb8411ca61ce) 
Current DCR: [`width=445` | `quality=85`](https://i.guim.co.uk/img/media/c3f2b5be3c0ff0a509fcce198ea36a40b79473fa/0_0_5025_3524/master/5025.jpg?width=445&quality=85&auto=format&fit=max&s=b5938b534b5cee57d3b84d084432f79f) 

_thumbnail (140 pixels)_
Frontend: [`width=300` | `quality=85`](https://i.guim.co.uk/img/media/220567fcc8d219a96815fc9754f9c6beb6e87f61/874_8_1478_1478/master/1478.jpg?width=300&quality=85&auto=format&fit=max&s=5a637d0f4d94c5f74aa07d3c35a72f07) 
New DCR: [`width=140` | `quality=45` | `dpr=2`](https://i.guim.co.uk/img/media/220567fcc8d219a96815fc9754f9c6beb6e87f61/874_8_1478_1478/master/1478.jpg?width=140&quality=45&auto=format&fit=max&dpr=2&s=69c9988b7b919bd8d34035e4122127d9) 
Current DCR: [`width=445` | `quality=85`](https://i.guim.co.uk/img/media/220567fcc8d219a96815fc9754f9c6beb6e87f61/874_8_1478_1478/master/1478.jpg?width=445&quality=85&auto=format&fit=max&s=f01ebcb4ea651e93616b67f36cbe6211) 

#### iphonex dpr3
_main media_
Frontend: [`width=2000` | `quality=85`](https://i.guim.co.uk/img/media/8b1d79d7b2db1f67f43b5bcb874735fc8202d90c/0_0_5791_3861/master/5791.jpg?width=2000&quality=85&auto=format&fit=max&s=8b208be0f257a0926cd7e1344186e1ce) 
New DCR: [`width=1125` | `quality=85`](https://i.guim.co.uk/img/media/8b1d79d7b2db1f67f43b5bcb874735fc8202d90c/0_0_5791_3861/master/5791.jpg?width=1125&quality=85&auto=format&fit=max&s=55832394389011865989bfd3543e413a)
Current DCR: [`width=445` | `quality=85`](https://i.guim.co.uk/img/media/8b1d79d7b2db1f67f43b5bcb874735fc8202d90c/0_0_5791_3861/master/5791.jpg?width=445&quality=85&auto=format&fit=max&s=583660f0ff0395e888526547a6c273cd)

_inline_
Frontend: [`width=445` | `quality=45` | `dpr=2`](https://i.guim.co.uk/img/media/833c4a3c34e8d98bcdde9c061e4e51630fac4cf5/0_174_3920_5215/master/3920.jpg?width=445&quality=45&auto=format&fit=max&dpr=2&s=716f8a4b816dfd1a586a490d794005e5)
New DCR: [`width=605` | `quality=45` | `dpr=2`](https://i.guim.co.uk/img/media/833c4a3c34e8d98bcdde9c061e4e51630fac4cf5/0_174_3920_5215/master/3920.jpg?width=605&quality=45&auto=format&fit=max&dpr=2&s=8b0a28501464de6c0e020edebf0a0212)
Current DCR: [`width=445` | `quality=85`](https://i.guim.co.uk/img/media/833c4a3c34e8d98bcdde9c061e4e51630fac4cf5/0_174_3920_5215/master/3920.jpg?width=445&quality=85&auto=format&fit=max&s=66e91635408beb4994da3a22e246049c)

#### galaxy s9 dpr4
_main media_
Frontend: [`width=2250` | `quality=85`](https://i.guim.co.uk/img/media/8b1d79d7b2db1f67f43b5bcb874735fc8202d90c/0_0_5791_3861/master/5791.jpg?width=2250&quality=85&auto=format&fit=max&s=19dc6fc2019319a76d694b693c1135e8)
New DCR: [`width=725` | `quality=45` | `dpr=2`](https://i.guim.co.uk/img/media/8b1d79d7b2db1f67f43b5bcb874735fc8202d90c/0_0_5791_3861/master/5791.jpg?width=725&quality=45&auto=format&fit=max&dpr=2&s=15f7c9a4df774ab237a7d122d42c0b02)
Current DCR: [`width=445` | `quality=85`](https://i.guim.co.uk/img/media/8b1d79d7b2db1f67f43b5bcb874735fc8202d90c/0_0_5791_3861/master/5791.jpg?width=445&quality=85&auto=format&fit=max&s=583660f0ff0395e888526547a6c273cd)

_inline_
Frontend: [`width=445` | `quality=45` | `dpr=2`](https://i.guim.co.uk/img/media/833c4a3c34e8d98bcdde9c061e4e51630fac4cf5/0_174_3920_5215/master/3920.jpg?width=445&quality=45&auto=format&fit=max&dpr=2&s=716f8a4b816dfd1a586a490d794005e5)
New DCR: [`width=620` | `quality=45` | `dpr=2`](https://i.guim.co.uk/img/media/833c4a3c34e8d98bcdde9c061e4e51630fac4cf5/0_174_3920_5215/master/3920.jpg?width=620&quality=45&auto=format&fit=max&dpr=2&s=5a993ef5e2aec4e7412ca928e00e2e18)
Current DCR: [`width=445` | `quality=85`](https://i.guim.co.uk/img/media/833c4a3c34e8d98bcdde9c061e4e51630fac4cf5/0_174_3920_5215/master/3920.jpg?width=445&quality=85&auto=format&fit=max&s=66e91635408beb4994da3a22e246049c)

_immersive_
Frontend: [`width=465` | `quality=45` | `dpr=2`](https://i.guim.co.uk/img/media/c3f2b5be3c0ff0a509fcce198ea36a40b79473fa/0_0_5025_3524/master/5025.jpg?width=465&quality=45&auto=format&fit=max&dpr=2&s=0ba76f27aceea32fff29dc76be3bf5fe)
New DCR: [`width=725` | `quality=45` | `dpr=2`](https://i.guim.co.uk/img/media/c3f2b5be3c0ff0a509fcce198ea36a40b79473fa/0_0_5025_3524/master/5025.jpg?width=725&quality=45&auto=format&fit=max&dpr=2&s=d987afa7cef931bbeeaea1b4e55a22da)
Current DCR: [`width=445` | `quality=85`](https://i.guim.co.uk/img/media/c3f2b5be3c0ff0a509fcce198ea36a40b79473fa/0_0_5025_3524/master/5025.jpg?width=445&quality=85&auto=format&fit=max&s=b5938b534b5cee57d3b84d084432f79f)

### CODE REVIEW

**Comment by paperboyo** [comment]
I welcome a closer look at (all) imagery! 👏 
I cannot comment on code changes and from cursory read, `img` indeed provides support for everything we were using `picture` for. 

Specifically,
> 2. Removing the `hdipi` related logic and adding the ability to create sizes.

as long as this replacement provides parity support for higher resolution when one uses a device with higher density screen (or zooms in low-density desktop over 133%) **and** we can still control distinctive “steps” of HiDPI support generically by manipulating fastly’s `dpr` attribute (instead of worrying about specific `width`s), ’ts cool.

My (poor!) understanding regarding
> Picture tags are useful for solving the art direction problem but are less useful where the focus is on saving bandwidth.

is that our use of `picture` provided everything to the browser to save the bandwidth, so this code change should be a no-op as far as readers are concerned (?).

**Comment by paperboyo** [comment]
cc @sndrs coz he was the author of initial implementation and ads are boring…

**Comment by paperboyo** [comment]
Related (beyond parity): https://github.com/guardian/frontend/issues/12216#issuecomment-196869603.

**Comment by gtrufitt** [comment]
For reference, here is why we moved from img -> picture in Frontend: https://github.com/guardian/frontend/pull/11400

**Comment by paperboyo** [comment]
> here is why we moved from img

Oh! Good find, I forgot completely. Makes sense. We don’t want a super-duper-highres phone to willy nilly pick up highest res source just because we provide one for half-super-duper desktops.

**Comment by JamieB-gu** [comment]
> For reference, here is why we moved from img -> picture in Frontend: [guardian/frontend#11400](https://github.com/guardian/frontend/pull/11400)

And here's why we moved from `img` -> `picture` in Apps-Rendering: https://github.com/guardian/apps-rendering/pull/327

**Comment by JamieB-gu** [comment]
> An `img` tag is less explicit about which source in the `srcset` to use, letting the browser to make the choice with the guide of `sizes` but also, potentially, using other information such as the reader's network conditions and what they might have in their cache.

This is interesting. The original reason we migrated from `img` to `picture` in Apps-Rendering was because we had no way to capture screen density using `srcset`, which meant we had no way to specify the `quality` parameter. We use the `quality` parameter because we have determined that we want:

- DPR 1 displays to use lower-res images, at higher quality (85%)
- DPR 2 (and higher) displays to use higher-res images, at lower quality (45%)

It was found that this provided the best balance of performance/bandwidth/noticeable image quality.

How does this change manage flipping between the two `quality` parameters?

**Comment by oliverlloyd** [comment]
Closing this in favour of `image-rendering` and based on discussions. See: https://docs.google.com/document/d/1LfSCS0e9KJFxQuehguEdYdbns_afDSrtxx8MI9zgiMg/edit

**Comment by oliverlloyd** [comment]
Ressurecting as a potential stopgap ahead of `image-rendering`

**Comment by oliverlloyd** [comment]
@paperboyo @sndrs @JamieB-gu We're thinking of moving ahead with this change as a stopgap ahead of migrating to `image-rendering`. There are some painfully poor quality images on DCR right now and this step improves our baseline.

**Comment by paperboyo** [comment]
This is great! It will be such a pleasure to finally see good quality images on DCR! Do you think it may make sense to spell out the two reasons we still think it makes sense to move to `picture` one day (for the future archaeologists)? IIUC, one Jamie gave [here](https://github.com/guardian/dotcom-rendering/pull/2067#issuecomment-727982211) and the other Gareth – [here](https://github.com/guardian/dotcom-rendering/pull/2067#issuecomment-727951084).

Thank you for the examples, this is very useful, one could almost imagine automated tests that would compare CSS widths (and one day heights too) of images at different breakpoints with actual requests made on certain devices. They should be able to help find inconsistencies and mistakes, like eg _iphonex dpr3: Main media_ which looks mad and wrong, but then you notice it’s a Photo essay – and everything suddenly makes sense, haha.

**Comment by oliverlloyd** [comment]
> Do you think it may make sense to spell out in the PR description the two reasons we still think it makes sense to move to `picture`

I've added to the description to make it clear what the future goals are

**Comment by oliverlloyd** [comment]
> one could almost imagine automated tests that would compare CSS widths of images at different breakpoints with actual requests made on certain devices

This would be a great contract to define. Eg.: If I have this device, at this screen width, and pass these srcsets, with this role, then I expect `src` to equal x. Superb idea.

**Comment by oliverlloyd** [comment]
> > one could almost imagine automated tests that would compare CSS widths of images at different breakpoints with actual requests made on certain devices
> 
> This would be a great contract to define. Eg.: If I have this device, at this screen width, and pass these srcsets, with this role, then I expect `src` to equal x. Superb idea.

Okay, so I don't think this is realistically possible. We want to test that various browsers, on different devices, at different breakpoints, do what we expect. But test automation in this field is typically done headless, where the presentation part of the browser is removed and the focus is on the html. We could (and do) use Storybook to render images at various breakpoints but we still can't assert these to check that the right image was picked.

Sadly, unless someone else has a better idea or wants to write some nifty pupetter script or something, I think this process will continue to be a manual. This PR lists a good baseline for this.

**Comment by paperboyo** [comment]
> Okay, so I don't think this is realistically possible.

Absolutely fine and kudos for having a look! In my naive mind I imagined two robots: first robot that builds `srcset`s based off designs at specific breakpoints in CSS pixels automagically (so that a rigid and arbitrary `ImageProfile.scala` goes away) and a second robot that runs through pages rendered on different devices and lists what browsers have chosen from the menu supplied by the first robot. And then us, humans, looking over the popularity histograms of the output of the second robot over months to make informed changes to what range and steps we want the first robot to provide.
But, you know, errare robotum est 😜.

**Review by jfsoul — APPROVED** [review]
I think this is a big improvement on the current situation, even if not the final solution. Great testing too, might even be worth pulling that procedure into a `testing image changes` advice doc.

**Comment by paperboyo** [comment]
👏 

Most popular inline images of 620px seem to be requested wrongly at 445px. But DPR 2 :-).

**Comment by oliverlloyd** [comment]
> 👏
> 
> Most popular inline images of 620px seem to be requested wrongly at 445px. But DPR 2 :-).
> EDIT: Example [URL](https://www.theguardian.com/politics/2020/dec/04/france-could-veto-bad-brexit-deal-macron-ally-warns), desktop widest breakpoint, zoomed in over 130% at dpr=2. Frontend serves 620px at dpr2.

I'm not able to replicate this; I'm getting the 620px, dp2 image everytime, on DCR, Frontend, same same. Is it still happening?

**Comment by oliverlloyd** [comment]
Is this because the browser is favouring a cached img that it has locally over making a network request? I think the spec talks about this functionality.

**Comment by paperboyo** [comment]
Pls disregard. On a third machine, it works correctly. Gremlins in the machine.

**Comment by JamieB-gu** [comment]
> Is this because the browser is favouring a cached img that it has locally over making a network request?

It's nice to see this happening in the wild. @paperboyo you can test this theory using the "Disable cache" checkbox in the Network tab of devtools (it will only disable it while the tools are open AFAIK).

**Comment by paperboyo** [comment]
Yeah, I disabled the cache. Done some more tests. My current operating hypothesis is that Firefox seems to be choosing sources differently from this (`img`) than from fontend (`picture`) where zoomed-in on a dpr 1 device. Chrome behaves as it did, as is Firefox on a genuine dpr 2 device.

As I’m permanently zoomed-in to 133% (dpr 1 device) on the Guardian, unfortunately I’m getting smaller images than on frontend. But:
- it’s much better than it used to be
- I hope that as soon as we move to `picture` again, I will be getting correct* sources

*correct means: when zoomed-in over 130% (or whatever media query specifies), on a dpr 1 device, request an image of CSS pixels width (strangely, this is the broken part, I’m getting 445px requests for inline article images of 620 CSS pixels!) at dpr 2.

**Comment by JamieB-gu** [comment]
> Firefox on a genuine dpr 2 device

If you drop into responsive design mode on Firefox (Cmd-Opt-M) there's a dropdown to simulate different DPRs, don't know if that's helpful?

**Comment by paperboyo** [comment]
Yeah, yeah, I know. But it doesn’t accept 1.3 which is what I would need to drop it down to on this machine I’m currently sitting on (drp 2) to simulate my home machines (both PC and Mac of dpr 1) being zoomed in over 130%.

Anyway :-). Can anyone with a Firefox on dpr 1 desktop can confirm 620px images are requested at 445px? (yes, I know, dpr 2, but still: too small dpr 2)

**Comment by oliverlloyd** [comment]
[Low quality images on DCR](https://trello.com/c/zUPi89R9/1817-low-quality-images-on-dcr)

**Pull request merged**
