### PR TITLE
Use ES2020 CMP

### PR DESCRIPTION
**Pull request by sndrs**
- bumps CMP to v6.0.0 
- bumps babel deps
- aligns storybook and main application webpack module config with https://github.com/guardian/frontend/pull/23011

### CODE REVIEW

**Comment by sndrs** [comment]
i wondered what this would be!

image

nearly 1kb for most people, pretty good

**Comment by liywjl** [comment]
there is an issue with chromatic CI, I cant seem to pin it down or get this issue to run locally @gtrufitt would you have any ideas?

**Comment by sndrs** [comment]
does anyone have any idea what might cause this?

**Comment by sndrs** [comment]
was able to get to the bottom of the error by running the same command the CI runs:

1. `yarn makeBuild`
2. `npm run build-storybook -- --output-dir /tmp/chromatic-3067py0VMzg4moOg` (omitting ` --silent`)

got me the following:

```bash
ERR! => Failed to build the preview
ERR! ./node_modules/@guardian/consent-management-platform/dist/index.esm.js 2:23
ERR! Module parse failed: Unexpected token (2:23)
ERR! You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
ERR! | const mark = (label) => {
ERR! >     window.performance?.mark?.(label);
ERR! | };
ERR! | 
ERR!  @ ./src/web/components/App.tsx 34:0-60 286:6-9
ERR!  @ ./src/web/components/HydrateApp.tsx
ERR!  @ ./src/web/layouts/Immersive.stories.tsx
ERR!  @ . sync \.stories\.tsx?$
ERR!  @ ./.storybook/config.js
ERR!  @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js
(node:8115) UnhandledPromiseRejectionWarning: [object Object]
(node:8115) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8115) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm ERR! code 1
npm ERR! path /Users/alex_sanders/Documents/code/dotcom-rendering
npm ERR! command failed
npm ERR! command sh -c node --max-old-space-size=4096 $(yarn bin)/build-storybook "--output-dir" "/tmp/chromatic-3067py0VMzg4moOg"

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alex_sanders/.npm/_logs/2020-09-23T12_28_32_781Z-debug.log
```

which suggests storybook webpack config might need to replicate the changes in #1919?

**Comment by sndrs** [comment]
sussed it! (thanks @SiAdcock) 

see `.storybook/webpack.config.js`

**Review by shtukas — APPROVED** [review]

**Review by liywjl — APPROVED** [review]

**Pull request merged**
