### PR TITLE
Turn On Square Ads Flag

### PR DESCRIPTION
**Pull request by JamieB-gu**
## Why?

We'd like to enable square ads in the first ad slot. We'll want to test this in CODE first.

## Changes

- Toggle the boolean flag that enables square ads.

### CODE REVIEW

**Comment by tahaamini** [comment]
Simulator Screen Shot - iPhone 11 - 2022-07-27 at 10 14 58
Simulator Screen Shot - iPhone 11 - 2022-07-27 at 10 15 11

This is how looks on iOS, going to do further testing on android as well

**Comment by tahaamini** [comment]
Template article :
Simulator Screen Shot - iPhone 12 - 2022-08-08 at 09 18 21


AR: 
Simulator Screen Shot - iPhone 12 - 2022-08-08 at 09 18 48


It is slightly cut off but I believe this is a native issue, teads verification method is passing also so I'm happy to approve this.

**Review by tahaamini — APPROVED** [review]
I was meant to add a review but accidentally moved it out of draft, sorry about that ! I've attached screenshots on how it looks, the ads are slightly cut off I believe this is a native issue and not related to this work, I'm happy to approve it, let me know what you think.

**Comment by JamieB-gu** [comment]
> I believe this is a native issue and not related to this work

Do we need to fix this before we turn this on?

**Comment by tahaamini** [comment]
> > I believe this is a native issue and not related to this work
> 
> Do we need to fix this before we turn this on (merge this PR)?

I spoke with commercial and we can merge this PR and work on the fix on the native side later

**Pull request merged**
