### PR TITLE
Bump `aws-cdk` To 1.147.0 And `@guardian/cdk` To 37.0.0

### PR DESCRIPTION
**Pull request by JamieB-gu**
## Why?

We want to bring our usage of GuCDK and `aws-cdk` up-to-date, because we're having issues with transitive dependencies on our current version. See #4139 (this PR should make that PR unnecessary). This update has actually removed the `vm2` dependency entirely.

## Changes

- Bumped `aws-cdk` and its related libraries to `1.147.0`
- Bumped `@guardian/cdk` to `37.0.0`
- Changed the location of the `AccessScope` import to reflect changes in https://github.com/guardian/cdk/pull/1105. @akash1810 does this look correct to you?
- Updated snapshots to use new VPC description to reflect changes in https://github.com/guardian/cdk/pull/1122
- Updated snapshots to reflect change in SSM parameter permission, as seen in https://github.com/guardian/cdk/pull/1076. @jacobwinch does this look correct to you?

### CODE REVIEW

**Review by nicl — APPROVED** [review]
Looks good to me from the DevX side. It is definitely a helpful reminder too that even changing a parameter description is a breaking change in the library as most teams will be using snapshot testing.

**Review by waisingyiu — APPROVED** [review]
Very clear description in the change list.  Thanks for the great work!

**Review by akash1810 — APPROVED** [review]
LGTM! How easy/difficult was it to find the PRs responsible for the breaking changes? And/or should we make the GuCDK release notes or change log better?

**Review by jacobwinch — APPROVED** [review]

**Comment by JamieB-gu** [comment]
Thanks everyone for the reviews!

> How easy/difficult was it to find the PRs responsible for the breaking changes? And/or should we make the GuCDK release notes or change log better?

I think it was reasonably easy 👍. We just worked through the notes on the GitHub releases page. Similar process to the one I usually follow for e.g. libraries that dependabot has opened PRs for. I haven't got anything specific that I think could be improved. @frankie297 @groakland any thoughts?

**Pull request merged**
