### PR TITLE
Pin the `yarn` binary version to v1.22.17

### PR DESCRIPTION
**Pull request by mxdvl**
## What does this change?

Bumps the yarn policy.

## Why?

When running commands, we currently have two versions of `yarn 1`: the latest `1.22` and the previously pinned `1.15`.

screenshot of conflicting yarn versions

Initially introduced in #1322

### CODE REVIEW

**Comment by OllysCoding** [comment]
Since yarn runs in the root directory now that we use yarn workspaces, should we move the .yarnrc to the root directory as well?

**Comment by mxdvl** [comment]
@OllysCoding any outstanding issue with merging this?

**Review by OllysCoding — APPROVED** [review]
+1 Go for it!

**Comment by mxdvl** [comment]
Thanks @JamieB-gu for bringing attention to this!

**Pull request merged**
