### PR TITLE
Remove E2E test for the puzzles banner

### PR DESCRIPTION
**Pull request by i-hardy**
## What does this change?

This removes the E2E Cypress test for the puzzles banner.

## Why?

We've turned this banner off via the switchboard, which has been causing this test to fail. While I think the code to load the banner should probably remain for the time being, I don't envision us turning it back on any time soon, so this test can be removed.

### CODE REVIEW

**Review by ioannakok — APPROVED** [review]
Thank you!

**Comment by mxdvl** [comment]
I think the UI Test check is hanging if there are no stories changed… annoying!

**Comment by i-hardy** [comment]
Any ideas on what to do about that?

**Comment by mxdvl** [comment]
I can merge as administrator … but that's not a long-term solution

**Pull request merged**
