### PR TITLE
Bump @babel/core to 7.22.6

### PR DESCRIPTION
**Pull request by AshCorr**
## What does this change?

- Bumps @babel/core to 7.22.6
- Drops `eslint-import-resolver-babel-module` in favour of `eslint-import-resolver-typescript`. The babel-module dependency has been archived and this dependency seems to break with the latest version of `babel-core`

## Why?

To hopefully fix the semver issue we've been seeing.

I don't really know why we needed to upgrade, I have a feeling that its because AR doesn't use pinned dependencies and also relies on @babel/core. My thinking is that Yarn thought it was ok to use @babel/core 7.22.6 even though we only wanted 7.22.5 in DCR because AR said it was ok to upgrade due to it being a patch version.

### CODE REVIEW

**Review by abeddow91 — APPROVED** [review]
Great work!

**Review by jamesgorrie — APPROVED** [review]
Neat.

If feels like a good choice as it's commonly used, and there aren't many alternative I can find. Was there any other reason to use it?

**Comment by AshCorr** [comment]
> If feels like a good choice as it's commonly used, and there aren't many alternative I can find. Was there any other reason to use it?

Not particularly, I just wanted to get our CI working again. I tried the webpack resolver too but it didn't seem to work properly without some more configuration, typescript worked straight out of the box so its what I went with.

**Comment by mxdvl** [comment]
Another example of `yarn`’s shameful hoisting biting us right in the deployment pipline…

**Pull request merged**
