### PR TITLE
feat: Replace editors with HAL 9000

### PR DESCRIPTION
**Pull request by AshCorr**
## What does this change?

Replace 90% of Journalists and Editors with HAL 9000. (We still need a few for images and article layout, but no more writers!)

## Why?

This will save us millions of £ every year in staffing costs.

### After

image

Demo link: https://3030.code.ashleigh.rocks/Article?url=https://www.theguardian.com/world/2022/mar/31/why-is-gchq-saying-putin-has-been-misinformed-about-ukraine-war

### CODE REVIEW

**Comment by OllysCoding** [comment]
This is genius! Am I correct in thinking that we might not need anywhere near as much dev work invested in editorial tools either?!

**Comment by AshCorr** [comment]
> Am I correct in thinking that we might not need anywhere near as much dev work invested in editorial tools either?!

Hadn't even thought of it from that angle! Yes I suppose so!

**Comment by arelra** [comment]
I like that HAL9000 is updating the article on every refresh, it keeps everything up to date!

I have a small suggestion though:

Could we add the article to a blockchain on every render as a replacement for our cache? 🤔

**Comment by AshCorr** [comment]
> I like that HAL9000 is updating the article on every refresh, it keeps everything up to date!

State of the art profiling, every reader sees a article tailored just for them!

**Comment by AshCorr** [comment]
This was an April fools PR 😀

**Pull request closed without merging**
