### PR TITLE
Fix AMP consent in ROW

### PR DESCRIPTION
**Pull request by Jakeii**
## What does this change?
Change the base amp consent config to match the current config for tcfv2, so that we get a tcfv2 consent banner everywhere that is not the US or Australia who have their own frameworks.

## Why?
Full exploration of this issue https://docs.google.com/document/d/11JxLXPx6N76UIj6qXtwf7gJx005QirXoB3V6zvly2R8/edit?usp=sharing

Any country not specified in the `amp-geo` config get's the base consent config, which appears to not contain enough detail for sourcepoint to present a consent banner.

The theory is that when [upgrading to sourcepoint's unified script](https://github.com/guardian/dotcom-rendering/pull/7818), something changed in sourcepoint's code that prevented the current base config from presenting a consent banner.

Have tested using VPN and Browserstack, locally and on CODE. In UK, US, AU, India, Turkey, and a few european countries.

If you're going to try this PR yourself, please note that you'll need to close and relaunch your incognito browser when switching regions, clearing data within the storage section of dev tools doesn't seem to fully clear the AMP region or consent.

### CODE REVIEW

**Comment by akinsola-guardian** [comment]
Thanks for fixing this. This looks sensible. Has this been tested using a VPN?

**Comment by Jakeii** [comment]
@akinsola-guardian Yes I've tested in a few country's and it works as expected.

**Review by arelra — APPROVED** [review]
Great investigation work on this @Jakeii !

**Review by SiAdcock — APPROVED** [review]
Lovely work @Jakeii

**Pull request merged**
