### PR TITLE
Replace `data-cy` with `data-testid`

### PR DESCRIPTION
**Pull request by arelra**
## What does this change?

Replace all `data-cy` attributes as we are migrating to [Playwright](#9420) as suggested by @georgeblahblah [here](https://github.com/guardian/dotcom-rendering/pull/9420#issuecomment-1803792951) .

I opted to replace it with with the more generic `data-testid` which is a convention used by [react-testing-library](https://testing-library.com/docs/queries/bytestid/).

Ideally we should move away from using specific test ids and assert on behaviour that [the user would see](https://playwright.dev/docs/best-practices#test-user-visible-behavior).

The `epic.interactivity.cy.js` `LiveBlogEpic` test still asserts on `data-cy` as it looks like its rendered output it not coming from DCR.

### CODE REVIEW

**Review by mxdvl — APPROVED** [review]
Sure thing!

**Comment by arelra** [comment]
> Why did we need to keep it for LiveBlog?

Also in the PR description:

The `epic.interactivity.cy.js` `LiveBlogEpic` test still asserts on `data-cy` as it looks like its rendered output it not coming from DCR.

**Comment by mxdvl** [comment]
> > Why did we need to keep it for LiveBlog?
> 
> Also in the PR description:
> 
> The `epic.interactivity.cy.js` `LiveBlogEpic` test still asserts on `data-cy` as it looks like its rendered output it not coming from DCR.

Should we fix it in https://github.com/guardian/support-dotcom-components/blob/92a7ae9ba46fb64440d50ae576b399e3e9f1e66f/packages/modules/src/modules/epics/ContributionsLiveblogEpic.tsx#L162 ?

**Comment by arelra** [comment]
> Should we [fix it upstream](https://github.com/guardian/support-dotcom-components/blob/92a7ae9ba46fb64440d50ae576b399e3e9f1e66f/packages/modules/src/modules/epics/ContributionsLiveblogEpic.tsx#L162)?

Good point will do

**Pull request merged**
