### PR TITLE
Add role attribute to unordered lists

### PR DESCRIPTION
**Pull request by MarSavar**
## What does this change?
Adds a `role="list"` to `<ul>` tags in AR components.

## Why?
Because Safari won't recognise them as lists if they are styled with `list-style: none`. 
See https://developer.mozilla.org/en-US/docs/Web/CSS/list-style#accessibility_concerns and #5041 for more details.

As described in the MDN docs, adding the role of list is necessary to avoid the issue in Safari.

## Screenshots

N/A

### CODE REVIEW

**Comment by MarSavar** [comment]
@mxdvl Would love to hear your thoughts on disabling the linting rule!

**Review by mxdvl — COMMENTED** [review]
While [the docs](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/no-redundant-roles.md) are not super clear, you can add an explicit key to the rule for `ul`:

```js
{
  'jsx-a11y/no-redundant-roles': [
    'error',
    {
      nav: ['navigation'],
      ul: ['list'],
    },
  ],
}
```

(unless I've misunderstood)

**Comment by MarSavar** [comment]
Thanks @mxdvl - that's exactly what I needed. Tested locally and it works!

**Review by mxdvl — APPROVED** [review]
Happy this worked!

**Pull request merged**
