### PR TITLE
Limit legacy interactive styling

### PR DESCRIPTION
**Pull request by nicl**
## What does this change?

Limts the global legacy styles:

* to scope to `body article`
* and only for 'legacy' interactives

## Why?

To avoid unfortunate side effects like introducing side scrolling on the footer (due to the change in box-model). E.g.

Screenshot 2021-08-18 at 14 35 49

### CODE REVIEW

**Comment by OllysCoding** [comment]
There's a lot of re-formatting going on here, is this something you were expecting, or is it a result of inconsistencies from the migration?

**Review by jlieb10 — APPROVED** [review]
@nicl the logic for loading and scoping the styles looks good to me, and makes a lot of sense. I am confused about all of the linting updates to `dotcom-rendering/index.d.ts` in this PR, though, and am curious if those are even the linting styles we normally use? They look a little bit odd, but I could be mistaken

**Review by DavidLawes — APPROVED** [review]
Thanks :)

**Comment by nicl** [comment]
@jlieb10 hey yeah, I *think* the formatting is related to the repo change yesterday. Will confirm before merging though as yeah did seem weird to me too. Thanks!

**Pull request merged**
