### PR TITLE
Dblatcher/screen reader promotion skip link

### PR DESCRIPTION
**Pull request by dblatcher**
## What does this change?
Wraps sign-up blocks  in a component that puts a visually hidden link pointing to a visually hidden element after the block: IE:
```
<a href="#EmailSignup-skip-link-12">skip past newsletter promotion</a>
<EmailSign />
<span id="EmailSignup-skip-link-12" tabindex="0">after newsletter promotion</span>
```

This is similar to how the "skip to main content" links work, and uses a variation of the  "visually hidden until focused on" styling they use.

The index in `renderElement` is used to ensure each skip link is unique.

## Why?
Allows screen reader user to avoid having the sign-up block read out every time. User help have received complaints about that.
The intent is to meet this specification: https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/G123

If the pattern works well for the `EmailSignUp` components, it could also be used to wrap other elements that could benefit from being skippable.

## Screenshot (used to the console to apply the focus styling on both elements to demonstrate)

Screenshot 2023-01-31 at 12 48 27

### CODE REVIEW

**Comment by rhystmills** [comment]
Do you have any advice on testing? Is there a standard article for dcr that contains the email block?

**Review by rhystmills — COMMENTED** [review]
Feels good via keyboard and screenreader. Great to be able to skip all that content. 

VoiceOver reads the 'after' `span` element a little strangely as "After" > "newsletter promotion" > "End of After newsletter promotion, group".

As a `p` element it just reads 'After newsletter promotion' which feels a bit neater. Obviously this will vary by screenreader.

Not sure which element feels more semantic though?

**Comment by dblatcher** [comment]
> Feels good via keyboard and screenreader. Great to be able to skip all that content and I'm sure the component could be used elsewhere in the same way.
> 
> VoiceOver reads the 'after' `span` element a little strangely as "After" > "newsletter promotion" > "End of After newsletter promotion, group".
> 
> Perhaps in part to do with the comment string that's getting generated here: image
> 
> By comparison, as a `p` element it just reads 'After newsletter promotion' which feels a bit neater. Obviously this will vary by screenreader.
> 
> Not sure which element feels more semantic though?

Thanks for looking - I think the 

> Feels good via keyboard and screenreader. Great to be able to skip all that content and I'm sure the component could be used elsewhere in the same way.
> 
> VoiceOver reads the 'after' `span` element a little strangely as "After" > "newsletter promotion" > "End of After newsletter promotion, group".
> 
> Perhaps in part to do with the comment string that's getting generated here: image
> 
> By comparison, as a `p` element it just reads 'After newsletter promotion' which feels a bit neater. Obviously this will vary by screenreader.
> 
> Not sure which element feels more semantic though?

Thanks for checking - I suspect we might be able to loose that comment string by rendering the all the text in a one template literal ( ```<span>{`after ${blockDescription}`</span>```) .Not sure about the semantics - if if needs to be a block level element to get the formatting right for the screen reader, maybe a `div` would be the right choice.

I'll take look and see what works out.

**Comment by dblatcher** [comment]
I've pushed a change to avoid that comment in the middle of the "after" text.

**Review by ioannakok — APPROVED** [review]
Great work! Tested locally and works really nice. One non-blocking question: Do you know why at the end it says "End of After newsletter promotion, group"? instead of "End of After newsletter promotion"

**Comment by rhystmills** [comment]
> Great work! Tested locally and works really nice. One non-blocking question: Do you know why at the end it says "End of After newsletter promotion, group"? instead of "End of After newsletter promotion"

I'm not sure of the exact cause - I've noticed it happens on VoiceOver for divs and spans with a tabindex but not a role, but not for a paragraph with a tabindex.

**Comment by dblatcher** [comment]
I've been trying to figure it out and find the ideal mark-up. As far as I can tell, screenreaders assign the generic role of 'group' to spans and divs, so this role gets announced when the element gets focus. I was trying to figure out if there's a suitable `role` attribute to use, but if using the paragraph element provides the best "announcement" I should probably go with that. Will push a change shortly

**Comment by dblatcher** [comment]
> I think it may be specifically VoiceOver, I tried NVDA and didn't find the 'group' issue occurring in spans and divs.

Thanks, @rhystmills. I've changed it to a paragraph to cover as many bases as possible. After looking through the options, it seemed to make sense to give it a role of "note" https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/note_role

**Pull request merged**
