### PR TITLE
Labs - Updates to standfirst and byline

### PR DESCRIPTION
**Pull request by rcrphillips**
This PR updates the standfirst and byline on photo essays labs articles in order to use the correct font based on the updated designs they've provided.

## Frontend
Screen Shot 2021-05-19 at 11 50 09

## Current DCR
Screen Shot 2021-05-19 at 11 50 26

## Now
Screen Shot 2021-05-18 at 11 03 25

### CODE REVIEW

**Comment by rcrphillips** [comment]
[Labs: font choice on standfirsts, bylines and rich links](https://trello.com/c/NRlWQC0F/196-labs-font-choice-on-standfirsts-bylines-and-rich-links)

**Comment by liywjl** [comment]
could you add a `before` and `after` screenshot?

**Comment by rcrphillips** [comment]
@liywjl have updated those screenshots

**Review by liywjl — APPROVED** [review]
LGTM 👍

**Pull request merged**
