### PR TITLE
Change the size of middots

### PR DESCRIPTION
**Pull request by nitro-marky**
## What does this change?

Changes the standfirst middot so it's the same size as the text.

### Before

Screenshot 2021-04-14 at 15 52 50

### After

Screenshot 2021-04-14 at 15 52 28

### CODE REVIEW

**Comment by nitro-marky** [comment]
https://trello.com/c/FzfTeb1E/2680-make-grey-standfirst-dot-the-same-height-as-the-capital-letter

**Comment by nitro-marky** [comment]
[Make Grey Standfirst dot the same height as the capital letter](https://trello.com/c/FzfTeb1E/2680-make-grey-standfirst-dot-the-same-height-as-the-capital-letter)

**Review by shtukas — APPROVED** [review]

**Review by liywjl — COMMENTED** [review]
Maybe use `px` instead? I cannot remember if we favour one over the other?

**Comment by nitro-marky** [comment]
> Maybe use `px` instead? I cannot remember if we favour one over the other?

Same here, I'll change to px and see if anyone gets enraged 😄

**Comment by paperboyo** [comment]
> I cannot remember if we favour one over the other?

No idea myself, but if one (or the other!) would mean that platform/browser/whatever font size setting would scale the type but not the dot or vice versa, I would always favour the one that would scale them both unison. Disregard if I’m spewing nonsense!

**Comment by oliverlloyd** [comment]
You should write your code in pixels because it's easier to read. But we want rems in the browser because that gets resized better, so we transform it at build time using this babel plugin https://github.com/guardian/babel-plugin-px-to-rem

Is that plugin working? Maybe not, I don't recall actually seeing rems in the browser but if that's so we should still maintain consistentsy by using pixels. We can look at fixing the plugin if needed.

**Pull request merged**
