### PR TITLE
Updated the InteractiveBlockComponent to render with `<island>` element

### PR DESCRIPTION
**Pull request by jlieb10**
Co-authored-by: Ioanna Kokkini <ioanna.kokkini@theguardian.com>
Co-authored-by: Oliver Lloyd <oliver.lloyd.freelancer@theguardian.com>

## What does this change?
We are rendering the InteractiveBlockComponent inside of an Island now instead of relying on the `HydrateOnce` or  `HydrateInteractiveOnce` method

## Why?
This solves a visual and semantic issue. These components were getting wrapped twice in a `<figure>` tag in order to contain them for the purposes of hydrating them. The effect this had was doubling the left margin on some of these elements, making them appear too small and out of place on the page.

### Before
Screenshot 2022-02-16 at 17 10 27

### After
Screenshot 2022-02-16 at 17 10 55

### CODE REVIEW

**Review by oliverlloyd — APPROVED** [review]
💯 on the code changes - this is super exciting to see working!

That Cypress test is failing because the element it is expecting to appear is not deferred until it is visible (`deferUntil="visible") on the `Island` so the failure is a good things and expected. I messaged you directly on how we can update the tests for this.

**Comment by mxdvl** [comment]
Could this solve https://github.com/guardian/frontend/issues/24659, @jamesgorrie ?

**Comment by ioannakok** [comment]
> Could this solve [guardian/frontend#24659](https://github.com/guardian/frontend/issues/24659), @jamesgorrie ?

I am quite sure it will!

**Comment by oliverlloyd** [comment]
Is this PR good to merge @ioannakok @jlieb10 ?

**Pull request closed without merging**
