### PR TITLE
Faux H3s

### PR DESCRIPTION
**Pull request by oliverlloyd**
## What?
Adds an enhancer step to replace `<p><strong>My Faux H3</strong></p>` with an actual `h3` element.

We area also prefixing this element with a `DividerBlockElement`

## Why?
To match the designs

## Why is the divider so short?
We only have one type of divider in DCR at the moment.We could look to add a full width one if needed, @HarryFischer ?

### CODE REVIEW

**Comment by oliverlloyd** [comment]
[Handle H3 elements](https://trello.com/c/KWHvL9cY/158-handle-h3-elements)

**Review by shtukas — APPROVED** [review]

**Comment by HarryFischer** [comment]
Yes please for divider - paragraph width would be best

**Review by liywjl — APPROVED** [review]
great work!! 👍

**Comment by oliverlloyd** [comment]
> Yes please for divider - paragraph width would be best

Righto, I've had this on my todo list for a while. I'll spin up a new PRand merge that one into this

**Pull request merged**
