### PR TITLE
Remove carousel AB test

### PR DESCRIPTION
**Pull request by buck06191**
## What does this change?
Removes Carousel AB test - related to https://github.com/guardian/frontend/pull/23588

## Why?
Test is done!

### CODE REVIEW

**Comment by buck06191** [comment]
[Tear down Carousel AB test](https://trello.com/c/tzGKQ16w/2700-tear-down-carousel-ab-test)

**Comment by oliverlloyd** [comment]
Can we also remove the other test related code? We added a lot of logic as a temporary solution to get the test running so ideally this PR - where we remove the test - is a good place to prevent that code living on when it no longer has a use case?

**Comment by buck06191** [comment]
> Can we also remove the other test related code? We added a lot of logic as a temporary solution to get the test running so ideally this PR - where we remove the test - is a good place to prevent that code living on when it no longer has a use case?

I can do that now, or I can extend the test in this PR and then handle the full tear down once we have results?

**Review by liywjl — APPROVED** [review]
👍

**Pull request merged**
