### PR TITLE
Thrasher tracker

### PR DESCRIPTION
**Pull request by mxdvl**
## What does this change?

Adds a script to measure the size of thrashers over time. From a mobbing session on 10% day last week.

## Why?

We want to know if they grow, reduce, or which ones to tackle first. Updates #5856 

## Example

> 
> ## [UK Front](https://www.theguardian.com/uk) 
> 
> | Name | Total size | Embed size | Resources |
> | ---- | ---------- | ---------- | --------- |
> | Documentaries | 901 kB | 25.4 kB | `woff2`: 391 kB, `mp4`: 288 kB, `jpg`: 196 kB, `js`: 1.54 kB |
> | First Edition newsletter | 381 kB | 30.8 kB | `woff2`: 300 kB, `png`: 40 kB, `js`: 9.65 kB |
> | Contact the Guardian | 325 kB | 22.7 kB | `woff2`: 300 kB, `js`: 1.92 kB |
> | Palette styles new do not delete | 112 kB | 111 kB | `js`: 962 B |
> | culture-treat | 103 kB | 9.79 kB | `png`: 89.8 kB, `js`: 2.82 kB, `gif`: 1.1 kB |

### CODE REVIEW

**Comment by paperboyo** [comment]
Interesting. Looks like reusing platform fonts would give us biggest gain?

**Comment by mxdvl** [comment]
> Interesting. Looks like reusing platform fonts would give us biggest gain?

It's not that simple, as 1 kB of JavaScript has to be parsed, evaluated and can load additional resources, whereas 100 kB of images or fonts can be cached, quickly processed and not load additional resources.

But in general, yes, sharing fonts would be a big win for some thrashers!

**Review by OllysCoding — APPROVED** [review]
I mobbed on this but it looks really good!

**Comment by OllysCoding** [comment]
> It's not that simple, as 1 kB of JavaScript has to be parsed, evaluated and can load additional resources ...

Also interesting, is that 'Embed size' is the size of the text getting added to the html page (prior to gzipping ofc!) - this then increases the size of the initial page request, slowing down nearly _all_ other parts of page loading. Getting rid of 'Palette styles do not delete' as part of the DCR migration will be a huge win!

**Comment by mxdvl** [comment]
> I mobbed on this but it looks really good!

Not only did you mob, you were the instigator 💎

**Pull request merged**
