### PR TITLE
Fix `KeyEvents` width

### PR DESCRIPTION
**Pull request by oliverlloyd**
## What does this change?
Removes a fixed width property from `KeyEvents`

## Why?
It was causing this element to overflow it's container

### Before
Screenshot 2022-02-21 at 21 22 21

### After
Screenshot 2022-02-21 at 21 22 54

### CODE REVIEW

**Review by ioannakok — APPROVED** [review]
👍

**Comment by oliverlloyd** [comment]
@JamieB-gu the AR stories look exploded on this but I think that's because there's no longer a width on this element and the stories don't have a container around them. I presume on the page this isn't an issue?

**Comment by JamieB-gu** [comment]
> the AR stories look exploded on this

Which stories are you talking about? I think the only AR-specific stories that contain this component are the liveblog layouts? 🤔

**Comment by oliverlloyd** [comment]
> > the AR stories look exploded on this
> 
> Which stories are you talking about? I think the only AR-specific stories that contain this component are the liveblog layouts? I can't see any diffs for them 🤔

As per our chat offline, from testing on CODE we're not seeing any AR issues with this change and the Chromatic diffs are only happening because the story is not bound by a container

**Pull request merged**
