### PR TITLE
Add CSS template block highlighting in vs code

### PR DESCRIPTION
**Pull request by sndrs**
## What does this change?

Add CSS template block highlighting in vs code

## Why?

was looking in here to see if you had a good one to do this but couldn't see anything

found this and really like it so thought might be useful

https://marketplace.visualstudio.com/items?itemName=jpoissonnier.vscode-styled-components

## Link to supporting Trello card

☠️ 🏴

### CODE REVIEW

**Comment by SiAdcock** [comment]
I’ve been using this too, it’s totally indispensable! Let’s get it in 👍

**Comment by sndrs** [comment]
yeah had a feeling it was prob old news :)

**Comment by SiAdcock** [comment]
[Ancient](https://github.com/guardian/source-components/commit/ec28945dbb502c71fe0f7fd0347e6009925a28d4), mate 😆 
 
Nice to see you around these parts, @sndrs!

**Comment by sndrs** [comment]
> Ancient, mate 😆

ha ha! no way!

**Comment by nicl** [comment]
@sndrs welcome back! :)

**Comment by gtrufitt** [comment]
YES

**Pull request merged**
