### PR TITLE
Remove `AnniversaryAtomComponent`

### PR DESCRIPTION
**Pull request by oliverlloyd**
## What does this change?
This PR removes the `AnniversaryAtomComponent` and associated code

## Why?
We're no longer showing this and are unlikely to have another 200 year anniversary

### CODE REVIEW

**Comment by oliverlloyd** [comment]
[Remove Anniversary Atom](https://trello.com/c/exUtozST/366-remove-anniversary-atom)

**Review by DavidLawes — APPROVED** [review]
👍  I don't think this component existed in amp, but did we have some associated svgs that can also be deleted (e.g. guardian-anniversary-logo.svg)?

**Review by lucymonie — APPROVED** [review]
LGTM

**Comment by oliverlloyd** [comment]
> 👍 I don't think this component existed in amp, but did we have some associated svgs that can also be deleted (e.g. guardian-anniversary-logo.svg)?

The anniversary logo is still in use. At some point we might think about refactoring the logo logic, bringing them all into Source? We were looking at this in the Identity team.

**Pull request merged**
