### PR TITLE
Move repo storybook to a new `storybooks` application

### PR DESCRIPTION
**Pull request by sndrs**
- creates a `storybooks` application that will eventually compose the individual application storybooks (for AR, DCR etc)
- temporarily relocates the existing global storybook to `storybooks` pending the creation of the app-based ones
- moves the deps installed in the root for the global storybook down into the packages that used them
	- more work to come on clearing up the rest of the root package deps

co-authored @joecowton1

### CODE REVIEW

**Review by mxdvl — APPROVED** [review]
This seems sound!

**Review by JamieB-gu — COMMENTED** [review]
Looks good.

I noticed that the key events stories seem to have picked up an underline (as seen in the Chromatic change check)? Is that intentional? @mxdvl I think you approved that change?

**Comment by mxdvl** [comment]
> Looks good.
> 
> I noticed that the key events stories have picked up an underline (as seen in the changes on the UI Tests check)? Is that intentional? cc @mxdvl

It’s flipped once or twice already, and I believe this is the old design for the key events, which is more @guardian/journalism-dev’s domain.

**Comment by JamieB-gu** [comment]
> this is the old design for the key events

It's the old design on dotcom, but the current design on the apps. The new key events timeline hasn't made it to apps yet.

> The underline was introduced to the subdued button variant in a recent Source update at the request of the design system team.

Ah, thanks for clarifying Joe!

> only used in the AR live blog so probably just a conversation to have with design before AR live blogs go live

Liveblogs and deadblogs share the same design, and deadblogs are currently in production on AR, so this key events component is in front of users.

**Comment by joecowton1** [comment]
> > Liveblogs and deadblogs share the same design, and deadblogs are currently in production on AR, so this key events component is in front of users.
> 
> Ah yes, good point. I just added to my above comment but i think we cross-posted.
> 
> The underline was introduced in source-react-component@9.0.0, which AR was already using so isn't added in this PR. I'm confused as to why you haven't been seeing the underline in your key events already, unless its already being overridden in AR?

@JamieB-gu @georgeblahblah The issue of underlines on the key events has been resolved along with other AR css issues by adding `babel-loader` to `common-rendering`.

**Review by georgeblahblah — APPROVED** [review]
Looks good! 📚

**Pull request merged**
