### PR TITLE
Increase amp padding to 20px.

### PR DESCRIPTION
**Pull request by AWare**
From 
image
To
image
Because it looks like this normally
image

### CODE REVIEW

**Comment by SiAdcock** [comment]
> it would only benefit mobile devices with a large (tablet/desktop size) width

Or mobile devices held in portrait orientation 😏

**Comment by walaura** [comment]
fwiw in `support-frontend` we scrapped the 20px-on-large-phones brekkypoint and it's a consistent 10px all the time – can't say design is enthused about it but the developers are 😅

**Comment by SiAdcock** [comment]
Shall we bin this change? Having a larger padding on a small number of wider mobile devices doesn't seem very important right now

**Comment by AWare** [comment]
binning as discussed

**Pull request closed without merging**
