### PR TITLE
datawrapper: Use dark background in dark mode

### PR DESCRIPTION
**Pull request by emdash-ie**
## What does this change?

This PR changes (only) datawrapper interactive block components to set a dark background in dark mode, instead of the white background currently set.

## Why?

At the moment, interactive block components set a white background in dark mode because interactive embeds are assumed not to handle dark mode.

This was done in https://github.com/guardian/dotcom-rendering/pull/10578, later modified in https://github.com/guardian/dotcom-rendering/pull/10580 to remove transparency.

This blocks the use of datawrapper’s automatic dark mode, because it causes it to display dark mode colours on a white background. This PR lets us use the automatic dark mode.

## Implementation Notes

I wasn’t entirely sure which colours to use: articleBackgroundDark seems the obvious choice (and is what I’ve gone with), but then why doesn’t interactiveBlockBackgroundList use articleBackgroundLight?

## Screenshots

| Before (auto dark mode on)      | After (auto dark mode on)      |
| ----------- | ---------- |
| ![before-auto-dark-on][] | ![after-auto-dark-on][] |

| Before (auto dark mode off)      | After (auto dark mode off)      |
| ----------- | ---------- |
| ![before-auto-dark-off][] | ![after-auto-dark-off][] |

[before-auto-dark-on]: https://github.com/user-attachments/assets/26209ec3-91aa-4690-afd6-7c312fcd933c
[after-auto-dark-on]: https://github.com/user-attachments/assets/b02f3d6a-8322-4eef-bc80-eca0f6dffebb
[after-auto-dark-off]: https://github.com/user-attachments/assets/2db55f87-b4fb-4699-8469-28694f915f3b
[before-auto-dark-off]: https://github.com/user-attachments/assets/8f87c72b-4d65-48e9-a083-0fa5f701ca0b

| Before (auto dark mode off; live blog)      | After (auto dark mode off; live blog)      |
| ----------- | ---------- |
| ![before-auto-dark-off-live-blog][] | ![after-auto-dark-off-live-blog][] |

| Before (auto dark mode on; live blog)      | After (auto dark mode on; live blog)      |
| ----------- | ---------- |
| ![before-auto-dark-on-live-blog][] | ![after-auto-dark-on-live-blog][] |

[before-auto-dark-off-live-blog]: https://github.com/user-attachments/assets/5ea88c0e-83ac-47e2-84ce-cce7ade7666f
[after-auto-dark-off-live-blog]: https://github.com/user-attachments/assets/8b7536f5-ed01-417d-b8d1-31289802c73c
[before-auto-dark-on-live-blog]: https://github.com/user-attachments/assets/446f10dc-5d4e-4326-9cdc-c46e035a9756
[after-auto-dark-on-live-blog]: https://github.com/user-attachments/assets/d46a0aa3-67f0-4ad6-855b-f69d1d7a4407

| Before (auto dark mode off; dead blog)      | After (auto dark mode off; dead blog)      |
| ----------- | ---------- |
|  | ![after-auto-dark-off-dead-blog][] |

| Before (auto dark mode on; dead blog)      | After (auto dark mode on; dead blog)      |
| ----------- | ---------- |
|  | ![after-auto-dark-on-dead-blog][] |

[after-auto-dark-off-dead-blog]: https://github.com/user-attachments/assets/5e7cca6d-cd99-4ab0-9943-4bd9bbb96f8b
[after-auto-dark-on-dead-blog]: https://github.com/user-attachments/assets/4f3f4329-b2de-4783-acc0-887169ae3621

Note: the “after” is using a local instance of DCR with frontend-CODE, which seems to cause the overlap error with the sidebar behind.

### CODE REVIEW

**Comment by emdash-ie** [comment]
I’d like to test this on articles with other background colours in dark mode. From [the definition of articleBackgroundDark](https://github.com/guardian/dotcom-rendering/blob/11ac3430625c2890eacf2956a629a17653b8968f/dotcom-rendering/src/palette.ts#L3051-L3078) it looks like this is dead blogs, live blogs, and any article when the theme is `SpecialReportAlt`. I’m not sure yet how to do the last of these – I’ll see if I can figure it out.

**Comment by emdash-ie** [comment]
I’d also like to see it in the apps in dark mode.

**Comment by emdash-ie** [comment]
Another thing has occurred to me that I should test: what happens to Datawrapper graphs that _don’t_ have auto dark mode enabled, in dark mode on this branch? (My worry is that we might get an unreadable graph using light-mode colours on a dark-mode background.)

**Comment by emdash-ie** [comment]
> Another thing has occurred to me that I should test: what happens to Datawrapper graphs that _don’t_ have auto dark mode enabled, in dark mode on this branch? (My worry is that we might get an unreadable graph using light-mode colours on a dark-mode background.)

Thankfully, this is not as bad as I had feared: there’s still a white background as there currently is. (Not ideal, but no worse than it currently is.) I’ve added screenshots of this to the PR description.

**Comment by emdash-ie** [comment]
> I’d also like to see it in the apps in dark mode.

Since the change should affect datawrapper graphics for which “auto dark mode” is enabled (and seeing specific articles from capi-CODE in the app seems like a big effort), I’m inclined to merge this before doing this check, and checking datawrapper graphics with “auto dark mode” enabled in the app in PROD (e.g. via the mystery bird article).

**Comment by emdash-ie** [comment]
> I’d like to test this on articles with other background colours in dark mode. From [the definition of articleBackgroundDark](https://github.com/guardian/dotcom-rendering/blob/11ac3430625c2890eacf2956a629a17653b8968f/dotcom-rendering/src/palette.ts#L3051-L3078) it looks like this is dead blogs, live blogs, and any article when the theme is `SpecialReportAlt`. I’m not sure yet how to do the last of these – I’ll see if I can figure it out.

I’ve tested live blogs and added screenshots to the PR description. Unfortunately the background colour is wrong and the graphic stands out from its background instead of blending in. Looks like the background is currently #000000 in this situation, but should be #1a1a1a.

**Review by domlander — APPROVED** [review]
> I wasn’t entirely sure which colours to use: articleBackgroundDark seems the obvious choice (and is what I’ve gone with), but then why doesn’t interactiveBlockBackgroundList use articleBackgroundLight?

I'm not sure what the answer to this is, but it looks like what you've done is sensible.

**Comment by emdash-ie** [comment]
Looking at dead blogs, they use the same card colour as live blogs (#1a1a1a), but a different background (#121212 for dead instead of #000000 for live). Since these graphics will be on the cards, I should update this to use the same #1a1a1a background for dead blogs as for live.

**Comment by emdash-ie** [comment]
> Looking at dead blogs, they use the same card colour as live blogs (#1a1a1a), but a different background (#121212 for dead instead of #000000 for live). Since these graphics will be on the cards, I should update this to use the same #1a1a1a background for dead blogs as for live.

I’ve made this update now in https://github.com/guardian/dotcom-rendering/pull/12831/commits/3a2fffdac82666ce292b59625e0f2f54b58ab0fb. I’ll take some screenshots when I get my hands on CODE.

**Comment by emdash-ie** [comment]
Here is what the updated colours look like on live blogs. First with auto dark mode on:

Screenshot 2024-11-14 at 17 01 17

Then with auto dark mode off:

Screenshot 2024-11-14 at 17 04 43

I’ll update these in the table above too, and do new ones for dead blogs.

**Comment by emdash-ie** [comment]
Here are two screenshots showing the new colours on dead blogs:

- first with automatic dark mode off

Screenshot 2024-11-14 at 17 11 24

- now with automatic dark mode on

Screenshot 2024-11-14 at 17 12 08

**Comment by emdash-ie** [comment]
@domlander Would you be ok to accept the pending changes in the UI tests? I’d like to have them accepted before merge if possible.

Unfortunately the Datawrapper embeds are not loading the second time in the snapshots, so we only see the background in the dark mode embed. But these changes do show the background colour changing. It would be nice for the storybook to more accurately reflect the site, so that the background colours match and the different background colours are tested. I’ll take a look and see what I can do.

**Comment by emdash-ie** [comment]
> It would be nice for the storybook to more accurately reflect the site, so that the background colours match and the different background colours are tested. I’ll take a look and see what I can do.

Gonna take a look in a separate PR and merge this now, I reckon!

**Comment by emdash-ie** [comment]
Auto dark mode looks good in the apps (testing in PROD with the mystery bird article now that the changes are out):

Datawrapper auto dark mode in app

**Comment by emdash-ie** [comment]
> Auto dark mode looks good in the apps (testing in PROD with the mystery bird article now that the changes are out) […]
> 
> Though the text could maybe be a bit brighter, it’s a little low-contrast.

I tested this in Android but not iOS, and it turns out that the font colour in iOS has not been responding to dark mode, resulting in black font disappearing on a black background. I'm looking into how to fix this fully, but in the mean time I'm going to revert this PR.

**Pull request merged**
