### PR TITLE
Adds support for Epic init functions

### PR DESCRIPTION
**Pull request by andre1050**
## What does this change?
Executes a JS snippet that may have been sent by the Contributions service via JSON. This will be used on some specific Epic variants to add the interaction needed on the client-side when just HTML & CSS isn't enough.

Only use case currently is when the Epic uses 'reminder fields' (i.e. has a form for the user to type in email address and submit to be reminded of making a contribution later on).

## Why?
Because we need support for the same Epic variants Frontend supports and some of them will simply need a bit of JS to run on the client-side.

## Notes
It's been agreed with the DCR team that we should move away from any approach that involves running JS code on the client outside of React. This PR is meant to be an interim solution to enable us to serve these interactive Epic variants in the short term until we tackle this issue more holistically in the near future.

## Context
The init function we call here only manages the form validation and submission, the toggling is CSS only. See the PR - https://github.com/guardian/contributions-service/pull/75

## Screenshots
Epic Reminder in default state (closed):
Screenshot 2020-03-23 at 16 35 34

Epic Reminder in open state:
Screenshot 2020-03-23 at 16 35 09

Epic Reminder in submitted state:
Screenshot 2020-03-23 at 16 26 07

### CODE REVIEW

**Comment by gtrufitt** [comment]
What happened to the `reportError`? on window?

**Comment by oliverlloyd** [comment]
> What happened to the `reportError`? on window?

Guess: it may have got lost in the transition to a smaller window object?

**Comment by andre1050** [comment]
Hello @oliverlloyd @gtrufitt - just letting you guys know we're preparing to merge this unless you have any last-minute objections. I know we're have multiple convos about this subject - running JS code outside of React - but I believe it's been agreed we'll use this approach temporarily until we find a better solution for rich components.

**Comment by gtrufitt** [comment]
🆒 Yes, discussed with Nic yesterday, sounds like that'll be following up in your priorities, so all good 🎆

**Pull request merged**
