### PR TITLE
update node to 18.16.0

### PR DESCRIPTION
**Pull request by georgeblahblah**
## What does this change?

- Updates node to `18.16.0`
- Updates DCR's AMI to [dotcom-rendering-ARM-jammy-node-18](https://amigo.gutools.co.uk/recipes/dotcom-rendering-ARM-jammy-node-18)
- Updates AR's AMI to [jammy-mobile-node18-ARM](https://amigo.gutools.co.uk/recipes/jammy-mobile-node18-ARM)
  - the AMI upgrades Node from `16` to `18`, and the Ubuntu version from `focal` to `jammy`. Possibly better to decouple this if we spot any problems!

Closes https://github.com/guardian/dotcom-rendering/issues/7577

## Why?

[Node 16 End of Life is approaching in September](https://nodejs.org/en/blog/announcements/nodejs16-eol). I think now is a good time to move to Node 18.

## How to test?

- [Successful DCR deploy to CODE](https://riffraff.gutools.co.uk/deployment/view/78469cd5-4d2f-4669-ace0-25c78e120653)
- [Successful AR deploy to CODE](https://riffraff.gutools.co.uk/deployment/view/575612ac-ee52-41b3-bace-03edc4b57dfe)

### CODE REVIEW

**Comment by georgeblahblah** [comment]
> Don't forget to bump the version in https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/Containerfile too!

@AshCorr definitely would have done!! Thanks

**Comment by JamieB-gu** [comment]
> Don't forget to bump the version in https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/Containerfile too!

@AshCorr is there any way we could derive this either from the `.nvmrc` or derive both from the same place?

**Review by AshCorr — APPROVED** [review]
🎉

**Comment by AshCorr** [comment]
> @AshCorr is there any way we could derive this either from the `.nvmrc` or derive both from the same place?

Yea, you could probably have a step just before the action that builds an image which does a Search & Relace to replace a placeholder version string in the Containerfile with the version in the .nvmrc

**Pull request merged**
