### PR TITLE
Correct typo

### PR DESCRIPTION
**Pull request by shtukas**

### CODE REVIEW

**Comment by SiAdcock** [comment]
Can we get rid of that `package-lock.json`? Can you remember how it was generated?

**Comment by shtukas** [comment]
Oh. I apologise for that. I committed it by accident. I will remove it in one second. 

By the way I asked you that question yesterday on chat

```
Pascal Honore: Yesterday 14:14
Question: the package-lock.json file (which showed up for me), should we .gitignore it or add it to git ?
```

I will investigate how I generated it and will come back to you

**Comment by shtukas** [comment]
@SiAdcock 
PR updated. 
... and the answer to your question is that package-lock.json was created when I ran `npm install [something]`

**Comment by SiAdcock** [comment]
Ah, sorry I missed that question @shtukas. Yeah, it's probably a good idea to `gitignore` it!

Since we're using Yarn, it's important to avoid running `npm install` to install dependencies locally, or to add dependencies to the project. Maybe we need to add specific documentation around this.

**Comment by shtukas** [comment]
> good idea to gitignore it!
> avoid running `npm install`
> Maybe we need to add specific documentation around this.

I will take care of that :)

**Pull request merged**
