### PR TITLE
Update to Source v7.x

### PR DESCRIPTION
**Pull request by sndrs**
## What does this change?

includes bump to v7 of source and dev kitchen for #12063

## Why?

to keep them up to date.

v7 also includes performance benefits to users and a reduced bundle size.

### CODE REVIEW

**Comment by sndrs** [comment]
i believe @jamesmockett will be considering the errors 😺

**Comment by abeddow91** [comment]
If its useful, @cemms1 did some work to bump source to v6 not too long ago @jamesmockett @sndrs https://github.com/guardian/dotcom-rendering/pull/12063 which might help with error fixes

**Comment by jamesmockett** [comment]
> If its useful, @cemms1 did some work to bump source to v6 not too long ago @jamesmockett @sndrs #12063 which might help with error fixes

Thanks @abeddow91 🙏 This PR branches off of Charlotte's work, so includes the fixes / updates she's already made. v7 introduces a bunch of new errors due to the removal of the typography API. I'll try and take a look at those later today and catch up with Charlotte.

**Comment by sndrs** [comment]
This PR should merge into Charlotte's PR too, in effect adding v7 stuff to her existing PR

**Comment by jamesmockett** [comment]
> I wonder if we should keep them separate rather than bundling all updates into one

It _might_ be simpler to update separately. I suppose we could update this branch from #12063 once you're happy with it and see how many more diffs we get in Chromatic?

**Comment by jamesmockett** [comment]
This has been superseded by #12342

**Pull request closed without merging**
