### PR TITLE
Feature/headline expanded link

### PR DESCRIPTION
**Pull request by andre1050**
## What does this change?
Extends the `SmallHeadline` component to allow further customisation of the link it renders when passed in a `linkTo` prop. The goal is to allow its `<a>` tag to have a hit area that expands beyond the boundaries of the `SmallHeadline` component itself. This is achieved by rendering a `::before` pseudo-selector for the `<a>` tag which uses absolute positioning to expand to the boundaries of the closest ancestor with a `position: relative`. This lets us interact with the entire row even though the actual `<a>` tag is rendered deeper inside the component structure.

As part of this refactor, `SmallHeadline` now accepts a new type called `HeadlineLink` to better encapsulate all props related to link handling in this context:

`
type HeadlineLink = {
    to: string;
    visitedColour?: string;
    expanded?: boolean;
};
`

## Why?
Because in some scenarios we want an entire area to be clickable, but we still want to make use of `SmallHeadline` which is rendered on a smaller area.

## Link to supporting Trello card
https://trello.com/c/SHiWSjWB/872-extend-smallheadline-component-to-allow-a-headline-link-to-use-a-different-colour-in-visited-state

### CODE REVIEW

**Comment by oliverlloyd** [comment]
My preference here is for the other, simpler, approach (already present in `master`), where you just naturally set the a link on the container and not change `SmallHeadline`. This would look like:

```
<a href="/my/card/wide/link">
  <p>Blah - I link to the card wide link</p>
  <SmallHeadline linkTo="/my/specific/link">
    If you hover me I'm styled with underline and I link to the specific link, even though I'm nested
  </Smallheadline>
</a>
```

The downside to this approach is that if your nested link is the same as the containing link, then you have 2 identical links so you are forced to repeat the setting of the a tag, one as the container wide link and one as the headline specific a tag. But I prefer this over creating a coupling between `SmallHeadline` and its parent.

**Comment by andre1050** [comment]
> My preference here is for the other, simpler, approach (already present in `master`), where you just naturally set the a link on the container and not change `SmallHeadline`. This would look like:
> 
> ```
> <a href="/my/card/wide/link">
>   <p>Blah - I link to the card wide link</p>
>   <SmallHeadline linkTo="/my/specific/link">
>     If you hover me I'm styled with underline and I link to the specific link, even though I'm nested
>   </Smallheadline>
> </a>
> ```
> 
> The downside to this approach is that if your nested link is the same as the containing link, then you have 2 identical links so you are forced to repeat the setting of the a tag, one as the container wide link and one as the headline specific a tag. But I prefer this over creating a coupling between `SmallHeadline` and its parent.

I agree avoiding this coupling between components is desired, but it is a coupling that's implemented explicitly through the props interface. Unlikely anybody would create such coupling unintentionally. The obvious upside to not needing nested links. In any case, `SmallHeading` needs to be expanded to allow a visited colour.

**Comment by oliverlloyd** [comment]
> SmallHeadline is expanded

The scary coupling is that the container is telling SmallHeadline to expand but SH will just blindly expand up to the first `position: relative` it hits - which, as people make styling changes,  could move 😱

**Comment by andre1050** [comment]
> > SmallHeadline is expanded
> 
> The scary coupling is that the container is telling SmallHeadline to expand but SH will just blindly expand up to the first `position: relative` it hits - which, as people make styling changes, could move 😱

Yeah that's very true and a perfectly valid concern. It's not the most _componenty_ approach ever.

**Comment by andre1050** [comment]
Going to close this PR as we've decided not to use this approach. Instead, we're merging https://github.com/guardian/dotcom-rendering/pull/941 to achieve the desired effect.

**Pull request closed without merging**
