### PR TITLE
Restructure server files to divide by purpose & better support multiple rendering targets

### PR DESCRIPTION
**Pull request by OllysCoding**
Please note: This PR is a step in the direction of an overall improved file structure. I will raise more in the coming days as well as I'm sure there will be more in the future as other ideas & imrpovements feed in. This is by no means the end goal of our file structure in CRP (DCR). 

This PR restructures the `server` directory in each of the 'web', 'amp' and 'apps' the following way:

'handle' files:
- `web/server/index.ts` -> `web/server/index.article.ts`, `web/server/index.front.ts`, `web/server/index.allEditiorialNewsletterPage.ts`
- `apps/server/index.ts` -> `apps/server/index.article.ts`
- `amp/server/index.ts` -> `amp/server/index.article.ts`

'[]toHtml` files
- `frontToHtml.tsx` -> `render.front.ts`
- `articleToHtml.tsx` -> `render.article.ts`
- `allEditorialNewslettersPageToHtml.tsx` -> `index.allEditorialNewslettersPage`

page template
- `pageTemplate.ts` -> `htmlPageTemplate.ts`

### What does this enable?

**DCAR**

As part of the DCAR project, we need to structure files in a way that allows for differences between web & apps targeted articles. After our RFC on this (https://github.com/guardian/dotcom-rendering/issues/7174) this PR takes us a step in the direction we need.

After this PR is merged we'll work on removing the `apps` directory, moving the existing apps files into the `web` directory, where `web/server/index.article.ts` would become `web/server/index.article.web.ts` & apps/server/index.article.ts` would become `web/server/index.article.apps.ts`.

The end goal will be to have a single flat structure in DCR (e.g no /web, /amp/, /apps, etc) and use `.web`, `.apps.` or `.amp` when there are distinctions between files.

**Future restructuring**

A future plan for DCR would be to break it down into purpose-driven-microservices, where each endpoint(s) would be it's own service with its own servers & loadbalancers; e.g fronts, article, interactives, etc.

This refactor supports this by beginning the process of breaking down the file structure to be more purpose-orientated.

### CODE REVIEW

**Review by georgeblahblah — APPROVED** [review]
This looks great! I think it makes so much sense! 

I also thought about nesting one more level, so something like:

```
web/
  server/
    article/
      index.ts
      render.ts
    front/
      index.ts
      render.ts
...
```

but maybe that's unnecessary for now! I like the `index.article.ts` pattern a lot, too.

**Comment by sndrs** [comment]
> I also thought about nesting one more level

I've been tempted by this in past, because it feels like it helps organise everything. 

but i've found it actually makes things a lot harder to find. you end up needing to know a lot of context to understand how to drill down, and there's obviously multiple way to categorise things. 

it doesn't always help to have everything in one folder, but i think it helps keep things more discoverable if we default to it

**Comment by georgeblahblah** [comment]
> because it feels like it helps organise everything

> you end up needing to know a lot of context to understand how to drill down

yes I see what you mean. Although it "feels nice" to me to add the extra nesting level here, it's probably a distraction and confusing, especially as this pattern grows

**Comment by OllysCoding** [comment]
Hi Both, I've merged this as-is for now & will revisit it once more of the 'restructuring' work is complete. I do like the 'tidiness' of folders, but share Alex's view that it can hurt discovery & understanding of the files

**Pull request merged**
