### PR TITLE
Automatically refresh fixtures

### PR DESCRIPTION
**Pull request by oliverlloyd**
## What?
Adds a new script to quickly fetch and refresh article fixture data

### Usage
`$ node scripts/test-data/gen-fixtures.js`

## Why?
Because doing this manually is time consuming and fiddly so it never happens, leading to our test content getting out of date,  reducing our test coverage.

### CODE REVIEW

**Review by shtukas — APPROVED** [review]

**Review by liywjl — APPROVED** [review]

**Review by gtrufitt — APPROVED** [review]

**Comment by oliverlloyd** [comment]
@gtrufitt am I adding this [post commit step](https://github.com/guardian/dotcom-rendering/pull/2510/commits/3f0f061de709230728d66796bf6f841858ffd273) right? I didn't see it run when I'm testing but I might be missing something?

**Comment by gtrufitt** [comment]
> @gtrufitt am I adding this [post commit step](https://github.com/guardian/dotcom-rendering/pull/2510/commits/3f0f061de709230728d66796bf6f841858ffd273) right? I didn't see it run when I'm testing but I might be missing something?

Don't you just need to add it to the `run-if-changed` step in package.json? https://github.com/guardian/dotcom-rendering/commit/929a0841997b60d21fe162d9bc90a2b65de99511#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R266 @oliverlloyd

**Comment by oliverlloyd** [comment]
> Don't you just need to add it to the `run-if-changed` step in package.json? [929a084#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R266](https://github.com/guardian/dotcom-rendering/commit/929a0841997b60d21fe162d9bc90a2b65de99511#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R266) @oliverlloyd

You mean remove the `git add` command and just leave it as calling the node script?

**Comment by oliverlloyd** [comment]
[Make updating article fixtures easier](https://trello.com/c/NYD6Pzjm/2435-make-updating-article-fixtures-easier)

**Pull request merged**
