### PR TITLE
Add updates after running `syncpack fix-mismatches` in root

### PR DESCRIPTION
**Pull request by gtrufitt**
Ensure that multiple packages requiring the same dependency define the same version.

Using https://github.com/JamieMason/syncpack

Note: I tried the other features of syncpack but I'm not sure we need them at this point.

### CODE REVIEW

**Comment by gtrufitt** [comment]
Thanks @PRBuilds (cc @MatthewJWalls 😁)

**Comment by nicl** [comment]
@gtrufitt should we run this as part of validate, or is it too slow?

**Comment by gtrufitt** [comment]
I was wondering, I think maybe running `syncpack list-mismatches` and failing, as that doesn't make code changes. It then I guess becomes a project dependency rather than global check. Will have a think.

**Comment by gtrufitt** [comment]
Gonna merge this, I'm not convinced of the value to add it as a project dependency though

**Pull request merged**
