### PR TITLE
Attempt at better rendering of quotes

### PR DESCRIPTION
**Pull request by shtukas**
## What does this change?

**->> Currently in production**:

Screenshot 2019-05-23 at 12 04 47

**->> DCR proposed change**

58263531-15630500-7d74-11e9-817c-3b19c2aa475d

### CODE REVIEW

**Comment by shtukas** [comment]
I have wasted enough time on this so I am proposing what  could do with CSS only.

**Comment by shtukas** [comment]
For reference here is how it currently done

Screenshot 2019-05-23 at 12 10 45

**Comment by shtukas** [comment]
@zeftilldeath We could pair on this one day. Not urgent right now :)

**Comment by zeftilldeath** [comment]
Can we use the quote icon we use on the website please?https://www.theguardian.com/uk/commentisfree

**Comment by shtukas** [comment]
I see... that's the same `svg` that we currently have on the liveblog. So I need to do some refactoring then...

**Comment by shtukas** [comment]
Been talking with @zeftilldeath and we agreed on this for the moment

Screenshot 2019-05-23 at 16 01 20

**Comment by zeftilldeath** [comment]
Nice Pascal. I think for the time being italicised text, indented is enough to show it's a quote. But I do think we should look into how we can get the right svg in here in the future.

**Pull request merged**
