### PR TITLE
`Design.Letter`

### PR DESCRIPTION
**Pull request by oliverlloyd**
## What does this change?
Adds support for `Design.Letter` to DCR

### Before
Screenshot 2021-04-06 at 11 58 37

### After
Screenshot 2021-04-06 at 11 56 17

## Why?
We were passing this value in as part of `format` but DCR didn't have any code to handle it. To get around this, we forced the value to be `Design.Comment`, which was similar, but not quite the same. By adding the display logic we allow full support.

### CODE REVIEW

**Comment by oliverlloyd** [comment]
["Letters" byline should be in left column](https://trello.com/c/btsoTcNe/2773-letters-byline-should-be-in-left-column)

**Review by jfsoul — APPROVED** [review]
👍

**Review by liywjl — APPROVED** [review]
LGTM

**Comment by buck06191** [comment]
[Letters format cleanup](https://trello.com/c/bPBm20Fq/2774-letters-format-cleanup)

**Comment by oliverlloyd** [comment]
[Letters format cleanup](https://trello.com/c/bPBm20Fq/2774-letters-format-cleanup)

**Pull request merged**
